- README.md
- benchmark/src/main/java/org/keycloak/benchmark/Config.java
- benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
- benchmark/src/main/scala/keycloak/scenario/admin/UserCrawl.scala
Hi,
created a new scenario to fetch users page by page. Numbers of users to fetch per page and number of pages to iterate over can be configured.
Kind regards
Benjamin
> User crawl scenario

- benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
- benchmark/src/main/scala/keycloak/scenario/admin/UserCrawl.scala
I'd like to change the user crawl scenario in a way that only one admin is crawling through the users. Our use case is actually one admin fetching all his users batch by batch which got very slow in Keycloak 13.
Also fetching new access tokens during the simulation to make sure we don't use expired ones.
> User crawl scenario constant number of admins (fetching the users)

- dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
When deleting large realms it might be useful to set the transaction timeout. The `DatasetConfig` also suggests that this query parameter is supported:
https://github.com/keycloak/keycloak-benchmark/blob/43e7ac21a146dbccc50c2c1e9564aa46b216ba67/dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java#L133-L136
> transaction timeout for realm deletion

- pom.xml
> Move to Java 11

- dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/ExecutorHelper.java
Unify user creation in create-realms an create-users endpoints: 
* better performance when creating realms with many users
* less code to maintain
Closes #38
> Unified user creation in create-realms and create-users endpoints

- dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java
Create groups in batches per transaction to avoid transaction timeouts when creating many groups.
> Added functionality to create groups in batches

- dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
Fix for https://github.com/keycloak/keycloak-benchmark/issues/45
> Fix for issue #45

- benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
- benchmark/src/main/scala/keycloak/scenario/_private/AdminConsoleScenarioBuilder.scala
As described in #46 , the `Date`header is not delivered anymore by Quarkus-based Keycloak.
This header was used in the scenario to compute the access token generation timestamp.
This PR computes this timestamp differently: it first stores the current timestamp in the session *before* the token request is performed, and *if successful*, then it stores the appropriate session attribute with the previously computed timestamp.
Benchmark scenarii now work as expected again - with both previous Keycloak versions and newer Quarkus-based versions.
Closes #46
> Date header is not delivered anymore in Keycloak responses and must not be used to compute access token generation time (fixes #46)

- benchmark/BENCHMARK.md
- benchmark/src/main/java/org/keycloak/benchmark/Config.java
- benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
- benchmark/src/main/scala/keycloak/scenario/admin/CreateDeleteRealms.scala
Scenario as described in #60
Closes #60
> Add a CreateDeleteRealms scenario to measure realm CRUD performance and concurrency capability (fixes #60)

- MAINTAINERS.md
I've added a maintainers file for this repo. 
It contains @pedroigor, @mposolda, @tkyjovsk, @kami619 and @ahus1 (me) 
I added everyone in the order they committed to this repository. Please let me know if you want a different order, don't want to be on the list, or want to be removed from the list.
I'll merge this PR sometime next week if I don't hear back from you.
Closes #48
> Add maintaners file similar to the Keycloak main repository.

- provision/minikube/README.adoc
> Update the docs on how to start the minikube dashboard

- provision/minikube/README.adoc
> Document how to use SSH port forwarding in a minikube remote setup.

- provision/minikube/README.adoc
- provision/minikube/keycloak/config/pgexporter-queries.yaml
- provision/minikube/keycloak/templates/postgres-exporter-configmap.yaml
- provision/minikube/keycloak/templates/postgres-exporter.yaml
> Gather metrics of PostgreSQL DB locks that have not yet been granted.

- provision/minikube/README.adoc
- provision/minikube/Taskfile.yaml
> Workaround for task being stuck when run on a single core.

- provision/minikube/README.adoc
- provision/minikube/Taskfile.yaml
- provision/minikube/isup.sh
- provision/minikube/jaeger/values.yaml
> Adding Jaeger retention in hours, not days

- provision/minikube/README.adoc
- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/config/cockroach-initdb.sql
- provision/minikube/keycloak/templates/NOTES.txt
- provision/minikube/keycloak/templates/cockroach/cockroach-configmap.yaml
- provision/minikube/keycloak/templates/cockroach/cockroach-deployment.yaml
- provision/minikube/keycloak/templates/cockroach/cockroach-ingress.yaml
- provision/minikube/keycloak/templates/cockroach/cockroach-nodeport.yaml
- provision/minikube/keycloak/templates/cockroach/cockroach-service.yaml
- provision/minikube/keycloak/templates/keycloak.yaml
- provision/minikube/keycloak/templates/postgres-deployment.yaml
- provision/minikube/keycloak/templates/postgres-exporter-configmap.yaml
- provision/minikube/keycloak/templates/postgres-exporter.yaml
- provision/minikube/keycloak/templates/postgres-service.yaml
- provision/minikube/keycloak/templates/sqlpad.yaml
- provision/minikube/keycloak/values.yaml
> Adding support for CockroachDB to the minikube setup

- provision/minikube/README.adoc
- provision/minikube/keycloak/templates/keycloak.yaml
- provision/minikube/keycloak/values.yaml
adding support for disabling caches using the values.yaml
______
Closes #151
> Add support for disabling caches using keycloak.yaml (fixes #151)

- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/templates/keycloak.yaml
> When the nightly build is missing, fallback to the previous release

- kcb-ci-runner.sh
enhanced the kcb-ci-runner.sh script.
Closes #143
> support different scenario params (fixes #143)

- dataset/dataset-import.sh
- doc/dataset/modules/ROOT/pages/index.adoc
> DatasetProvider import automation - main simple operations

- kcb-ci-runner.sh
hotrod map storage support for the CI script
_____________________________________________
Closes #180
> hotrod map storage support for the CI script (fixes #180)

- provision/minikube/keycloak/templates/infinispan/infinispan-deployment.yaml
> Upgrading to Infinispan/HotRod version to 13.0.10.Final

- dataset/dataset-import.sh
- doc/dataset/modules/ROOT/pages/index.adoc
This PR is built on top of the previous PR: https://github.com/keycloak/keycloak-benchmark/pull/177 and it refactors the case command, documentation and mainly the create-realms function.
> Dataset script - documentation/create-realms (refactoring #177)

- provision/minikube/Taskfile.yaml
- provision/minikube/loki.yaml
- provision/minikube/promtail.yaml
> Pin the versions of the different helm charts and fix the loki values

- benchmark/src/main/resources/gatling.conf
> Updating default values in gatling.conf

- benchmark/src/main/content/bin/initialize-benchmark-entities.sh
- benchmark/src/main/java/org/keycloak/benchmark/Config.java
- benchmark/src/main/scala/keycloak/scenario/CommonSimulation.scala
- benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
- benchmark/src/main/scala/keycloak/scenario/_private/OIDCRegisterAndLogoutSimulation.scala
- benchmark/src/main/scala/keycloak/scenario/admin/UserCrawl.scala
- benchmark/src/main/scala/keycloak/scenario/authentication/LoginUserPassword.scala
- doc/benchmark/modules/ROOT/pages/configuration.adoc
- doc/benchmark/modules/ROOT/pages/scenario/authorization-code.adoc
> Update scenarios to support logout with the new post_logout_redirect_uri parameter

- benchmark/pom.xml
> Minimize dependencies for a smaller JAR

- kcb-ci-runner.sh
update CI runner to support authentication scenarios
___________________________________________
Closes (#227)
> update CI runner to support authentication scenarios (fixes #227)

- doc/kubernetes/modules/ROOT/pages/index.adoc
- doc/kubernetes/modules/ROOT/pages/installation.adoc
- doc/kubernetes/modules/ROOT/partials/isup-now-working-macros.adoc
> Update docs to alert users about a known issue with kubernetes installation on MacOS

- doc/kubernetes/modules/ROOT/pages/index.adoc
- doc/kubernetes/modules/ROOT/pages/installation.adoc
- doc/kubernetes/modules/ROOT/partials/isup-bash-version-macos.adoc
- doc/kubernetes/modules/ROOT/partials/isup-now-working-macros.adoc
> [224] .isup working details for macOS

- dataset/dataset-import.sh
> Wrong getopt args evaluation fixed - using shift for optional args.

- benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
- benchmark/src/main/scala/keycloak/scenario/admin/ListSessions.scala
- doc/benchmark/modules/ROOT/nav.adoc
- doc/benchmark/modules/ROOT/pages/scenario-overview.adoc
- doc/benchmark/modules/ROOT/pages/scenario/authorization-code.adoc
- doc/benchmark/modules/ROOT/pages/scenario/list-sessions.adoc
> Add a new admin scenario to list client and user sessions under that realm

- doc/kubernetes/modules/ROOT/nav.adoc
- doc/kubernetes/modules/ROOT/pages/error-messages.adoc
- doc/kubernetes/modules/ROOT/pages/load-behavior.adoc
> Document Keycloak behavior under load

- doc/kubernetes/modules/ROOT/nav.adoc
- doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
- doc/kubernetes/modules/ROOT/pages/util/custom-image-for-keycloak.adoc
- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/templates/keycloak.yaml
- provision/minikube/keycloak/values.yaml
> Add a guide on how to build a local Keycloak image and use it in minkube

- .github/workflows/provision-minikube.yml
- dataset/dataset-import.sh
Improves the status-completed endpoint to poll on the task till success is returned
Adds a new endpoint function to clear the last status completed record
Closes #196
> Adding dataset-import task creating realms on each storage

- provision/minikube/monitoring/dashboards/keycloak-perf-tests.json
> Updating metrics after change to Micrometer

- .github/workflows/build.yml
- dataset/pom.xml
- dataset/src/test/java/org/keycloak/benchmark/it/DeploymentIT.java
- doc/dataset/modules/ROOT/pages/building-provider.adoc
- doc/dataset/modules/ROOT/pages/changing-provider.adoc
- doc/dataset/modules/ROOT/pages/using-provider.adoc
- pom.xml
Also adding a scheduled build every week.
Closes #267
> Add integration test for dataset module

- provision/minikube/Taskfile.yaml
- provision/tlsdisableagent/buildtlsagent.sh
> Avoid concurrent download of maven wrapper

- dataset/src/main/java/org/keycloak/benchmark/cache/CacheResourceProviderFactory.java
- dataset/src/main/java/org/keycloak/benchmark/cache/RemoteCacheResourceProviderFactory.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/AuthorizationProvisioner.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProviderFactory.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/RealmContext.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/TaskManager.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/config/ConfigUtil.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetOperation.java
* Please, see #287 for the reasoning
* I'm also including a commit with the necessary changes to align the JAX-RS-related code in the dataset with the latest changes from upstream. Let me know if you want a separate PR.
> Allow provisioning authorization settings for a client

- .github/workflows/provision-minikube.yml
- dataset/dataset-import.sh
- doc/benchmark/modules/ROOT/pages/scenario/list-sessions.adoc
- doc/dataset/modules/ROOT/pages/using-provider.adoc
- doc/kubernetes/modules/ROOT/pages/util/task.adoc
> dataset-import script refactoring

- dataset/src/main/java/org/keycloak/benchmark/dataset/AuthorizationProvisioner.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java
> Make sure user policy creation take into the account the number of users per realm

- .github/workflows/provision-minikube.yml
- doc/kubernetes/modules/ROOT/pages/storage/cockroach-operator.adoc
- provision/minikube/keycloak/templates/cockroach-operator/cockroach-operator.yaml
- provision/minikube/rebuild.sh
> Update CockroachDB Operator version v2.10.0

- doc/kubernetes/modules/ROOT/pages/util/custom-image-for-keycloak.adoc
- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/operator-patch.yaml
- provision/minikube/keycloak/templates/keycloak.yaml
- provision/minikube/rebuild.sh
Fix scripts and docs when working with custom Keycloak images.
> Enhancements and fixes to run custom Keycloak images

- .github/workflows/provision-minikube.yml
> Disable CRDB in GitHub action until upstream issue is fixed

- .github/workflows/provision-minikube.yml
> Re-enabling CRDB tests after upstream fix

- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/templates/postgres/postgres-deployment.yaml
- provision/openshift/Taskfile.yaml
> Clean and faster restart of PostgreSQL on OpenShift

- benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
- benchmark/src/main/scala/keycloak/scenario/admin/HomePage.scala
> Adding a new homepage scenario in admin

- doc/kubernetes/modules/ROOT/nav.adoc
- doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
- doc/kubernetes/modules/ROOT/pages/openshift.adoc
- doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-openshift.adoc
- provision/openshift/Taskfile.yaml
- provision/openshift/cluster-monitoring-config.yaml
- provision/openshift/grafana.yaml
- provision/openshift/monitoring/Chart.yaml
- provision/openshift/monitoring/dashboards/keycloak-perf-tests.json
- provision/openshift/monitoring/templates/dashboards-json-configmap.yaml
> Add documentation on how to connect to OpenShift

- doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
- provision/minikube/keycloak/templates/keycloak-initial-admin-secret.yaml
- provision/minikube/keycloak/values.yaml
- provision/openshift/Taskfile.yaml
- provision/openshift/grafana.yaml
> Do not use default security in openshift

- .github/workflows/rosa-run-benchmark.yml
Closes #356
ps. there is no cluster online so I haven't tested it yet. Will do it tomorrow.
> Make Keycloak cluster size configurable

- .github/workflows/rosa-run-benchmark.yml
* CPU and Memory
* Custom Keycloak image
* Fixed Openshift project name
> New inputs for benchmark workflow

- doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
- provision/common/Taskfile.yaml
- provision/minikube/keycloak/templates/keycloak.yaml
- provision/minikube/keycloak/values.yaml
- provision/openshift/Taskfile.yaml
Closes #359
Draft PR because I haven't had time to test it. Early feedback is welcome.
> Disable sticky session in Openshift Route

- .github/workflows/keycloak-scalability-benchmark-on-schedule.yml
> Schedule daily run of scalability benchmark

- .github/workflows/rosa-cluster-create.yml
- provision/minikube/isup.sh
- provision/openshift/isup.sh
Creation succeeded: https://github.com/ahus1/keycloak-benchmark/actions/runs/5354012504
Running a benchmark succeeded: https://github.com/ahus1/keycloak-benchmark/actions/runs/5354666431/jobs/9711992746
Closes #388
> Upgrade to OpenShift 4.12.21

- .github/workflows/rosa-cluster-create.yml
- .github/workflows/rosa-cluster-delete.yml
- doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-rosa.adoc
- provision/aws/efs/.gitignore
- provision/aws/efs/aws-efs-csi-driver-operator.yaml
- provision/aws/efs/credentialRequests/openshift-aws-efs-csi-driver-credential-request.yaml
- provision/aws/efs/efs-csi-aws-com-cluster-csi-driver.yaml
- provision/aws/rosa_create_cluster.sh
- provision/aws/rosa_delete_cluster.sh
- provision/aws/rosa_efs_create.sh
- provision/aws/rosa_efs_delete.sh
- provision/aws/rosa_efs_test.sh
- provision/aws/rosa_oc_login.sh
- provision/aws/rosa_recreate_admin.sh
There was a successful create run here to create one cluster here: https://github.com/ahus1/keycloak-benchmark/actions/runs/5347697967/jobs/9696556604
There was a successful run to delete the cluster here: https://github.com/ahus1/keycloak-benchmark/actions/runs/5349788947/jobs/9701503197
To test a Pod with EFS based PVCs, there is a script `rosa_efs_test.sh`.
Closes #386
> Support EFS on ROSA for ReadWriteMany PVCs

- benchmark/src/main/content/bin/kc-chaos.sh
- provision/aws/rosa_create_cluster.sh
- provision/aws/rosa_delete_cluster.sh
Any idea for a nicer fix? I think it is important to have the date and time there.
> Do not use colon in archived log files

- doc/kubernetes/modules/ROOT/pages/installation-openshift.adoc
- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/templates/keycloak.yaml
- provision/minikube/monitoring/dashboards/client-credentials-otel.json
- provision/openshift/Taskfile.yaml
- provision/openshift/grafana.yaml
- provision/openshift/monitoring/templates/jaeger-pvc.yaml
> Adding Jaeger to the observability stack on OpenShift

- .github/actions/keycloak-create-dataset/action.yml
- .github/workflows/keycloak-chaos-benchmark.yml
- .github/workflows/keycloak-create-dataset.yml
- .github/workflows/keycloak-scalability-benchmark.yml
- benchmark/src/main/content/bin/kcb.sh
Closes #397
Successful runs in my repo: 
* https://github.com/ahus1/keycloak-benchmark/actions/runs/5392627085/jobs/9791243862
* https://github.com/ahus1/keycloak-benchmark/actions/runs/5390338223/jobs/9786067498
> Adding waiting time for entity creation as a parameter

- provision/aws/rosa_efs_create.sh
- provision/aws/rosa_efs_delete.sh
> Wait for termination of file system as it might block VPC deletion

- ansible/.gitignore
- ansible/README.md
- ansible/ansible.cfg
- ansible/aws_ec2.sh
- ansible/aws_ec2.yml
- ansible/benchmark.sh
- ansible/benchmark.yml
- ansible/env_example.yml
- ansible/requirements.yml
- ansible/roles/aws_ec2/README.md
- ansible/roles/aws_ec2/defaults/main.yml
- ansible/roles/aws_ec2/tasks/create-resources.yml
- ansible/roles/aws_ec2/tasks/delete-resources.yml
- ansible/roles/aws_ec2/tasks/main.yml
- ansible/roles/aws_ec2/tasks/manage-instances.yml
- ansible/roles/aws_ec2/templates/inventory.yml.j2
- ansible/roles/benchmark/README.md
- ansible/roles/benchmark/defaults/main.yml
- ansible/roles/benchmark/tasks/install-locally.yml
- ansible/roles/benchmark/tasks/install.yml
- ansible/roles/benchmark/tasks/main.yml
- ansible/roles/benchmark/tasks/run.yml
- ansible/roles/benchmark/templates/gatling.j2.rc
> Distributed Gatling

- .github/workflows/rosa-cluster-create.yml
- doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-rosa.adoc
Closes #403
Successful runs: 
* Create cluster: https://github.com/ahus1/keycloak-benchmark/actions/runs/5420966074
* Deploy Keycloak: https://github.com/ahus1/keycloak-benchmark/actions/runs/5421591107
> Upgrade to OpenShift to 4.13.4

- provision/aws/rosa_create_cluster.sh
- provision/infinispan/install_operator.sh
> Install Infinispan operator

- .github/workflows/keycloak-create-deployment.yml
- doc/kubernetes/modules/ROOT/pages/installation-openshift.adoc
- doc/kubernetes/modules/ROOT/pages/util/cryostat.adoc
- provision/aws/rosa_create_cluster.sh
- provision/aws/rosa_install_certmanager_operator.sh
- provision/aws/rosa_install_cryotstat_operator.sh
- provision/common/Taskfile.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-command-service.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-cr.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-deployment.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-grafana-basic.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-grafana-service.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-ingress.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-jfr.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-pvc.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-rolebindings.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-roles.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-service.yaml
- provision/minikube/keycloak/templates/cryostat/cryostat-serviceaccount.yaml
- provision/openshift/Taskfile.yaml
- provision/openshift/isup.sh
Will run tests via GHA to ensure this works. Will then switch to non-draft and merge.
Successful cluster creation with Operators installed: https://github.com/ahus1/keycloak-benchmark/actions/runs/5462268361
Successful deployment including CryoStat: https://github.com/ahus1/keycloak-benchmark/actions/runs/5462867412/jobs/9942805028
Closes #414
> Adding cryostat to OpenShift deployment

- provision/aws/efs/aws-efs-csi-driver-operator.yaml
- provision/aws/rosa_create_cluster.sh
- provision/aws/rosa_efs_create.sh
- provision/aws/rosa_install_certmanager_operator.sh
- provision/aws/rosa_install_cryotstat_operator.sh
- provision/aws/rosa_install_openshift_logging.sh
- provision/infinispan/install_operator.sh
> Make rosa_create_cluster.sh idempotent

- provision/infinispan/Utils.yaml
- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/infinispan/ispn-helm/values.yaml
Depends on https://github.com/keycloak/keycloak-benchmark/pull/457
> Enable namesAsTags for Infinispan cluster

- .github/workflows/rosa-cluster-create.yml
- doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-rosa.adoc
> Update to 4.13.6 version of ROSA

- .github/workflows/README.md
> Fix README that wrongly suggests to set AWS_REGION for workflows

- provision/infinispan/README.adoc
- provision/infinispan/Utils.yaml
- provision/infinispan/ispn-helm/templates/infinispan.yaml
* CPU and Memory request and limit
* Java Options
* Added precondition for the main tasks
* Added cross-site mode (sync/async)
> More options for Infinispan deployment

- provision/infinispan/Utils.yaml
- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/infinispan/ispn-helm/values.yaml
Only the first cluster deploys the Gossip Router
> Infinispan deploy only a single Gossip Router globally

- .github/actions/prometheus-metrics-calc/action.yml
- .github/workflows/rosa-scaling-benchmark-on-schedule.yml
- .github/workflows/rosa-scaling-benchmark.yml
Added Schedule run config for Rosa scalability benchmark
> Update ROSA scalability workflow to commit the result numbers to github

- doc/benchmark/modules/ROOT/pages/configuration.adoc
- doc/benchmark/modules/ROOT/pages/report/rosa-benchmark-key-results.adoc
> update rosa benchmark key results doc with refresh token results

- provision/rosa-cross-dc/Taskfile.yaml
* route53 -> creates the Route53 DNS records
* monitoring -> installs grafana in both ROSA clusters
* dataset-import -> triggers the user creation in the primary cluster
> Added more task to rosa-cross-dc Taskfile.yaml

- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/infinispan/ispn-helm/values.yaml
- provision/rosa-cross-dc/Taskfile.yaml
Fixes #551
Unrelated changes include:
* Added task to create/delete EC2 VMs
* Added task to run the benchmark in EC2 VMs
* Added task to fetch the Grafana dashboards into PDF file for both clusters (thanks @kami619 )
* Added task to trigger failover
> Configure conflict resolution for ASYNC

- doc/kubernetes/modules/ROOT/pages/running/infinispan-crossdc-deployment.adoc
- doc/kubernetes/modules/ROOT/pages/running/infinispan-deployment.adoc
- doc/kubernetes/modules/ROOT/partials/running/infinispan-attributes.adoc
- doc/kubernetes/modules/ROOT/partials/running/infinispan-credentials.adoc
Added documentation on how to check if the deployment is successful.
> Docs: verify Infinispan deployment

- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/openshift/Taskfile.yaml
> Expose the http rest endpoint to get access to interact with the ISPN caches

- doc/kubernetes/collector/build.sh
- doc/kubernetes/modules/ROOT/pages/running/failover-recovery.adoc
- doc/kubernetes/modules/ROOT/pages/running/index.adoc
- doc/kubernetes/modules/ROOT/pages/running/infinispan-crossdc-deployment.adoc
- doc/kubernetes/modules/ROOT/pages/running/network-partition.adoc
- doc/kubernetes/modules/ROOT/pages/running/switch-back.adoc
- doc/kubernetes/modules/ROOT/pages/running/switch-over.adoc
- doc/kubernetes/modules/ROOT/partials/aurora/aurora-failover.adoc
- doc/kubernetes/modules/ROOT/partials/running/infinispan-batchcr-intro.adoc
- doc/kubernetes/modules/ROOT/partials/running/infinispan-running-batch.adoc
- provision/infinispan/ispn-helm/templates/infinispan.yaml
I changed existing docs to SYNC cross-site replication and added the manual steps for Infinispan to recovery from some scenarios.
> Infinispan operational guide

- .github/workflows/rosa-run-crossdc-func-tests.yml
- dataset/pom.xml
- dataset/src/test/java/org/keycloak/benchmark/it/DeploymentIT.java
- dataset/src/test/java/org/keycloak/benchmark/test/ExecutorTest.java
- dataset/src/test/java/org/keycloak/benchmark/test/FinderTest.java
- pom.xml
- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/README.md
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/pom.xml
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/run-crossdc-tests.sh
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/CrossDCTest.java
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/DatacenterInfo.java
> CrossDC functional test suite automation

- .github/workflows/rosa-run-crossdc-func-tests.yml
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/CrossDCTest.java
Successful Run: https://github.com/kami619/keycloak-benchmark/actions/runs/7034987240/job/19144310299#step:10:54
Signed-off-by: Kamesh Akella <kamesh.asp@gmail.com>
> Fixing GH workflow and code issues around cross dc tests

- provision/aws/route53/route53_create.sh
- provision/minikube/keycloak/templates/keycloak.yaml
Relates to keycloak/keycloak#25077
> Update resource path to use '/lb-check'

- .github/workflows/rosa-scaling-benchmark.yml
- provision/infinispan/Taskfile.yaml
- provision/infinispan/Utils.yaml
With xsite disabled the benchmark took ~40 minutes to populate the dataset.
https://github.com/ryanemerson/keycloak-benchmark/actions/runs/7101660153/job/19330256218
> Disable xsite communication before initializing dataset

- .github/workflows/rosa-run-crossdc-func-tests.yml
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/pom.xml
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/run-crossdc-tests.sh
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/CrossDCTest.java
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/DatacenterInfo.java
> adding create entities methods

- provision/infinispan/Utils.yaml
- provision/infinispan/sa-token-secret.yaml
> Create non-expirable SA token for cross-site

- provision/rosa-cross-dc/Taskfile.yaml
Related to
https://github.com/keycloak/keycloak-benchmark/commit/0598144ef9f3ef31f2edf48a5bb0accd334a0bc7
https://github.com/keycloak/keycloak-benchmark/commit/5e88c4ab1414b6b106e6d862017cd98a0b69c37e
> Use non-expiring token for Grafana and HTTPS

- provision/minikube/keycloak/templates/keycloak.yaml
Relates to keycloak/keycloak#26223
Closes #604
> Use the http-max-queued-requests option for load shedding

- provision/infinispan/Utils.yaml
* Added the missing `KUBECONFIG` otherwise it uses the one defined in your machine
* Set `defer` after the creation of the `Batch` command.
> Add missing KUBECONFIG to kubectl commands

- provision/rosa-cross-dc/Taskfile.yaml
* Added user-per-sec and duration
* Added refresh token count and period
> Add support for more benchmark options

- provision/rosa-cross-dc/Chaos.yaml
- provision/rosa-cross-dc/Taskfile.yaml
Added tasks to randomly kill pods (gossip router, infinispan or keycloak).
https://github.com/krkn-chaos/krkn-hub/tree/main
> Integrate with Kraken-Chaos

- .github/actions/prepare-horreum-report/action.yml
- .github/actions/prometheus-metrics-calc/action.yml
- .github/workflows/rosa-multi-az-cluster-create.yml
- .github/workflows/rosa-multi-az-cluster-delete.yml
- .github/workflows/rosa-multi-az-cluster-undeploy.yml
- .github/workflows/rosa-scaling-benchmark.yml
- provision/common/Taskfile.yaml
- provision/infinispan/Utils.yaml
- provision/rosa-cross-dc/Taskfile.yaml
> Rosa Scaling Benchmark: JSON Update with environment data

- provision/rosa-cross-dc/Taskfile.yaml
* Added KUBECONFIG otherwise it uses the default
* Delete the configmap before creating a new one
> Fix some error with environment configmap

- .github/workflows/rosa-multi-az-cluster-create.yml
- .github/workflows/rosa-multi-az-cluster-undeploy.yml
- .github/workflows/rosa-run-crossdc-func-tests.yml
> fix missing Java version dependencies and clear up some text in GHW

- .github/actions/prepare-horreum-report/action.yml
- .github/actions/prometheus-metrics-calc/action.yml
- .github/workflows/rosa-scaling-benchmark.yml
- provision/common/Taskfile.yaml
- provision/rosa-cross-dc/Taskfile.yaml
The PR includes the processing of Gatling report and including the statistics to report JSON file, as well as the fixes of the remarks on json keys and values.
> Rosa Scaling Benchmark: JSON Update with latency numbers from Gatling report (#635)

- provision/minikube/keycloak/templates/keycloak.yaml
Please don't merge this PR yet because it doesn't work with the current nightly build.
Two things are necessary before merging:
1. This PR: https://github.com/keycloak/keycloak/pull/26682 or any equivalent fix needs to be merged in Keycloak main and it must be merged at the time when no-one works today as this will break deployments with current KC nightly. However, it needs to be merged before tomorrow morning because otherwise, tomorrow's scheduled run will fail
2. This PR https://github.com/keycloak/keycloak/pull/26666 needs to be merged
> Use new Infinispan config options

- provision/minikube/keycloak/templates/keycloak.yaml
Closes #704
Here is the corresponding change in the Keycloak repository that builds on these changes: 
https://github.com/keycloak/keycloak/pull/26777
> Update docs for new supported Infinispan options

- .gitignore
- provision/rosa-cross-dc/Taskfile.yaml
Keycloak deployed in parallel instead of sequentially
> Refactor Keycloak deployment

- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/infinispan/ispn-helm/values.yaml
* remote-timeout set to 5 seconds
* lock acquire-timeout set to 4 seconds
* cross-site timeout set to 4.5 seconds
> Reduce Infinispan timeouts

- doc/kubernetes/collector/build.sh
- provision/keycloak-tasks/Utils.yaml
- provision/minikube/keycloak/templates/keycloak.yaml
- provision/minikube/keycloak/values.yaml
This PR consists of KCB changes needed for this main KC repo PR: https://github.com/keycloak/keycloak/pull/27236
> Documentation for using AWS JDBC Wrapper

- doc/kubernetes/modules/ROOT/pages/running/index.adoc
- doc/kubernetes/modules/ROOT/pages/running/timeout_tunning.adoc
Needs to be moved to a proper place...
> JGroups failure detection configuration

- doc/kubernetes/modules/ROOT/pages/util/healthchecks-keycloak.adoc
- doc/kubernetes/modules/ROOT/partials/util-nav.adoc
- provision/rosa-cross-dc/cross-site-health-checks.sh
> health check docs

- dataset/pom.xml
Should resolve #726 .
Signed-off-by:Tomas Kyjovsky <tkyjovsk@redhat.com>
> Added a direct dependency on `commons-io:2.15.1` to the `dataset` module

- .github/workflows/rosa-cluster-create.yml
- provision/opentofu/modules/rosa/hcp/variables.tf
Resolves #742 
https://github.com/ryanemerson/keycloak-benchmark/actions/runs/8536543888
> Upgrade to OpenShift 4.15.3

- doc/kubernetes/modules/ROOT/pages/util/healthchecks-keycloak.adoc
- provision/rosa-cross-dc/cross-site-health-checks.sh
> Align health checks used by Keycloak as the management port is not available anymore

- doc/kubernetes/modules/ROOT/pages/openshift/installation-openshift.adoc
- provision/keycloak-tasks/Utils.yaml
- provision/keycloak-tasks/olm.sh
- provision/keycloak-tasks/olm/templates/operatorgroup.yaml
- provision/keycloak-tasks/olm/templates/subscription.yaml
- provision/openshift/Taskfile.yaml
- provision/openshift/isup.sh
Backport of OLM support into the `0.12-release` branch, including 2 subsequent fixes.
> Support for installing Keycloak Operator via OLM for the `0.12-release` branch.

- .github/workflows/rosa-cluster-create.yml
- provision/aws/rosa_delete_cluster.sh
- provision/opentofu/destroy.sh
Closes #810
Please find the successful run with this changes here: https://github.com/andyuk1986/keycloak-benchmark/actions/runs/9070651045
>  Daily scheduled cluster deletion job fails

- doc/kubernetes/modules/ROOT/pages/openshift/cross-site-rosa.adoc
Those hints were missing and cost me some extra time when creating the cluster today.
> Add steps for Route53 LB to cross-site ROSA

- provision/aws/rosa_delete_cluster.sh
>  Unable to remove ROSA cluster due to osd-network-verifier SecurityGroup

- dataset/pom.xml
- dataset/src/test/java/org/keycloak/benchmark/test/KeycloakServer.java
- pom.xml
Signed-off-by: Pedro Igor <pigor.craveiro@gmail.com>
Closes #850
> Allow running embedded server from IDE

- .github/workflows/rosa-multi-az-cluster-undeploy.yml
Undeploy of an A/A cluster on my fork: https://github.com/ryanemerson/keycloak-benchmark/actions/runs/9661372368
> rosa-multi-az-cluster-undeploy.yml fails for Active/Active deployments

- dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
> Fixing search by group name qhen creating groups

- README.adoc
- doc/ROOT/modules/ROOT/pages/index.adoc
- doc/benchmark/modules/ROOT/pages/release.adoc
> release docs updated

- provision/opentofu/modules/rosa/hcp/variables.tf
Deployment on my fork https://github.com/ryanemerson/keycloak-benchmark/actions/runs/9854270905
> Openshift 4.16.0

- provision/opentofu/modules/rosa/hcp/variables.tf
This reverts commit a481235e014ddd194de42182814ea17b58621517.
Closes #898
> Revert "Openshift 4.16.0 (#892)"

- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/ConcurrentModificationTest.java
> Add test for concurrent client session addition

- provision/infinispan/Utils.yaml
- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/infinispan/ispn-helm/values.yaml
> Throw an error when Cross-DC operations fail

- ansible/roles/benchmark/README.md
- ansible/roles/benchmark/defaults/main.yml
working run : https://github.com/kami619/keycloak-benchmark/actions/runs/10304044625/job/28521526303
> update ec2 runner to jdk21

- provision/infinispan/ispn-helm/templates/infinispan-alerts.yaml
> Endpoint in global accelerator is missing after functional tests are run

- provision/infinispan/ispn-helm/values.yaml
> Reverting to an old setup where keep all sessions in memory on the Infinispan side of things

- dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java
- dataset/src/main/java/org/keycloak/benchmark/dataset/organization/OrganizationIdentityProviderProvisioner.java
- doc/dataset/modules/ROOT/pages/using-provider.adoc
Closes keycloak/keycloak#31736
> Enhance benchmark dataset to include IDP mappers for the IDPs

- doc/kubernetes/collector/build.sh
- pom.xml
- provision/infinispan/Utils.yaml
- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/infinispan/ispn-helm/values.yaml
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/ExternalInfinispanClient.java
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/util/HttpClientUtils.java
> Remove sessions caches from KCB when Persistent Sessions is enabled

- doc/kubernetes/modules/ROOT/pages/util/kc-chaos.adoc
> Add docs for the Krkn Chaos pod scenarios against Keycloak in K8s setup

- provision/infinispan/Utils.yaml
- provision/infinispan/ispn-helm/values.yaml
- provision/rosa-cross-dc/Taskfile.yaml
CPU: 2 requested, max of 4
Memory: 1GB requested, max of 2GB
offtopic, updated benchmark defaults to match the GH actions nightly runs.
> Limit Infinispan cluster resources

- .github/workflows/rosa-cluster-auto-provision-on-schedule.yml
Fixes #980 
Individual workflow works as expected - https://github.com/keycloak/keycloak-benchmark/actions/runs/10907745335/job/30272134584 
Adding the health checks to the ROSA Scheduled workflow.
> Update the ROSA Scheduled workflow to include Health Checks

- dataset/src/main/java/org/keycloak/benchmark/dataset/organization/OrganizationIdentityProviderProvisioner.java
> Provisioning organization brokers to now shown on login pages by default

- doc/kubernetes/modules/ROOT/pages/running/metrics/keycloak_with_external_infinispan.adoc
- doc/kubernetes/modules/ROOT/partials/running/metrics/ispn_metrics.adoc
- doc/kubernetes/modules/ROOT/partials/running/metrics/jgrp_metrics.adoc
- doc/kubernetes/modules/ROOT/partials/running/metrics/kc_hot_rod_client_metrics.adoc
* Hide Hot Rod metrics (reason: not released yet)
* Fix missplaced endif
* Add largest JGroups thread pool size metric
* Add hit and success ratios example to Hot Rod metrics
> Feedback on Metrics

- .github/workflows/README.md
- .github/workflows/keycloak-scalability-benchmark.yml
- .github/workflows/rosa-cluster-create.yml
- .github/workflows/rosa-multi-az-cluster-create.yml
- doc/benchmark/modules/ROOT/pages/report/rosa-benchmark-key-results.adoc
- doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-rosa.adoc
- provision/aws/rosa_create_cluster.sh
- provision/opentofu/modules/rosa/hcp/variables.tf
> Fixes #1002, updating the EC2 workerpool type for ROSA HCP cluster nodes

- dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
KeycloakModelUtils.runJobInTransactionWithResult() method changed it signature
offtopic: changed `collect(Collectors.toList())` to `toList()` just to get rid of the IDE warning :)
> Fix compile error

- provision/infinispan/Utils.yaml
- provision/infinispan/ispn-helm/values.yaml
> Update Infinispan to 15.0.10.Final

- .github/actions/ec2-create-instances/action.yml
- .github/actions/ec2-delete-instances/action.yml
- ansible/aws_ec2.sh
This fix comes from @ryanemerson commit: https://github.com/ryanemerson/keycloak/commit/8174bb26932cba2b8ad984d073ae20f34ba038a4 
Tested in my personal GHA: https://github.com/mhajas/keycloak-benchmark/actions/runs/11326943860/job/31496938839
> Fix error creating EC2 runner instances

- provision/minikube/keycloak/templates/keycloak.yaml
> Remove http-pool-max-threads configuration

- doc/kubernetes/modules/ROOT/pages/running/metrics/jvm_metrics.adoc
- provision/minikube/monitoring/dashboards/keycloak-status.json
Closes #1042
Dashboard screenshot:
> Add Kubernetes CPU metric to JVM metric guide and dashboard

- provision/minikube/monitoring/dashboards/keycloak-status.json
With current version error response percentage looks broken. It seems `OR on() vector(0)` does not work as expected, I removed it.
> Fix error responses percentage

- doc/kubernetes/modules/ROOT/partials/running/metrics/kc_enable_metrics.adoc
- provision/minikube/keycloak/templates/keycloak.yaml
> enable the event metrics for users by default

- provision/infinispan/Utils.yaml
- provision/infinispan/ispn-helm/templates/infinispan.yaml
- provision/infinispan/ispn-helm/values.yaml
Closes  #1066
It is not tested yet, but something along these lines would be enough.
> OTEL Tracing for Infinispan

- provision/minikube/monitoring/dashboards/keycloak-user-events.json
- provision/openshift/monitoring/dashboards/keycloak-user-events.json
> add a starter dashboard for user event metrics

- .github/workflows/provision-minikube.yml
- provision/common/Taskfile.yaml
- provision/keycloak-tasks/Utils.yaml
- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/templates/keycloak.yaml
- provision/minikube/keycloak/values.yaml
- provision/minikube/rebuild.sh
- provision/openshift/Taskfile.yaml
> Enable NetworkPolicy by default

- benchmark/src/main/python/generate_timeseries_plots.py
- benchmark/src/main/python/requirements.txt
- doc/kubernetes/modules/ROOT/pages/util/perf-insights.adoc
A small python utility that I am using to visualize time series plot for custom dataset window and it would generate graphs like below.
> add a python script which supports creating plot graphs on the data generated from perfInsights.py

- .github/workflows/rosa-cluster-auto-provision-on-schedule.yml
<!! MERGE IT ON THE DAY FROM WHICH WE WANT TO DISABLE THE JOB>
> Disable rosa-cluster-auto-provision-on-schedule.yml for the holidays.

- .github/workflows/auto-delete-on-schedule.yml
> Fix tofu not removing accelerators

- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/templates/postgres/postgres-deployment.yaml
- provision/minikube/keycloak/templates/sqlpad.yaml
- provision/minikube/loki.yaml
- provision/minikube/monitoring.yaml
- provision/minikube/monitoring/templates/graphite-exporter.yaml
- provision/minikube/promtail.yaml
- provision/openshift/Taskfile.yaml
- provision/openshift/grafana.yaml
> Move away from DockerHub for used images

- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/ConcurrentModificationTest.java
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/ExternalInfinispanClient.java
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/InfinispanClient.java
> Add authentication sessions concurrency test

- provision/infinispan/ispn-helm/templates/infinispan.yaml
> Enable virtual threads in the Infinispan cluster

- provision/infinispan/ispn-helm/values.yaml
Closes keycloak/keycloak#37253
> Upgrade Infinispan to 15.0.13.Final

- doc/benchmark/modules/ROOT/pages/configuration.adoc
- doc/benchmark/modules/ROOT/pages/downloading-benchmark.adoc
- doc/benchmark/modules/ROOT/pages/index.adoc
- doc/benchmark/modules/ROOT/pages/preparing-keycloak.adoc
- doc/benchmark/modules/ROOT/pages/report/result-summary.adoc
- doc/benchmark/modules/ROOT/pages/scenario-overview.adoc
- doc/dataset/modules/ROOT/pages/changing-provider.adoc
- doc/dataset/modules/ROOT/pages/index.adoc
- doc/kubernetes/modules/ROOT/examples/_README.adoc
- doc/kubernetes/modules/ROOT/pages/alternatives.adoc
- doc/kubernetes/modules/ROOT/pages/index.adoc
- doc/kubernetes/modules/ROOT/pages/installation-minikube.adoc
- doc/kubernetes/modules/ROOT/pages/limitations.adoc
- doc/kubernetes/modules/ROOT/pages/other.adoc
- doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-kubectl.adoc
- doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-minikube.adoc
- doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-yq.adoc
- doc/kubernetes/modules/ROOT/pages/running/timeout_tuning.adoc
- doc/kubernetes/modules/ROOT/pages/util/custom-image-for-keycloak.adoc
- doc/kubernetes/modules/ROOT/pages/util/debugging-keycloak.adoc
This PR include several small changes to documentation to improve reading as well as fixes to the text, e.g, reference to a wrong parameter.
> Minor fixes of documentation

- provision/keycloak-tasks/olm.sh
Not needed anymore. Issue has been solved since KC 24.
> Remove workaround for Keycloak issue #28638.

- benchmark/src/main/content/bin/initialize-benchmark-entities.sh
> Fix creation of clients in initialize-benchmark-entities.sh

- provision/infinispan/ispn-helm/values.yaml
Closes https://github.com/keycloak/keycloak/issues/40481
> Upgrade to Infinispan 15.0.16.Final

- pom.xml
- provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/pom.xml
Closes #1164
There has been a successful run of the functional tests here: https://github.com/keycloak/keycloak-benchmark/actions/runs/16374822445/job/46272599359
> Fixing problem with classpath dependencies

- pom.xml
- provision/infinispan/ispn-helm/values.yaml
Closes keycloak/keycloak#41257
> Upgrade to Infinispan 15.0.18.Final

- .github/actions/ec2-create-instances/action.yml
- .github/actions/ec2-delete-instances/action.yml
- .github/workflows/rosa-multi-az-clusters_single-site-run-benchmark.yml
- .github/workflows/rosa-scaling-benchmark.yml
- ansible/aws_ec2.sh
- ansible/benchmark.sh
> Environment variable for cluster identifier

- pom.xml
- provision/infinispan/ispn-helm/values.yaml
Closes keycloak/keycloak#41934
> Upgrade to Infinispan 15.0.19.Final

- provision/minikube/Taskfile.yaml
- provision/minikube/keycloak/templates/postgres/postgres-deployment.yaml
- provision/openshift/Taskfile.yaml
Signed-off-by: Ryan Emerson <remerson@ibm.com>
> Utilise StatefulSet for Postgres so that data survives restart
