keycloak/keycloak-benchmark

dataset/src/main/java/org/keycloak/benchmark/cache/CacheResourceProvider.java
dataset/src/main/java/org/keycloak/benchmark/cache/RemoteCacheResource.java
dataset/src/main/java/org/keycloak/benchmark/dataset/TaskManager.java
pom.xml

* Introduced InfinispanUtilProxy to abstract access to InfinispanUtil that is located in different packages in KC < 16 and KC >= 16

Fix keycloak-benchmark to run also with keycloak 16

---

pom.xml

Hi,
using "16.0.0-SNAPSHOT" doesn't work anymore and bumping the versions to "16.1.0" resolves the issues so here's the required adjustment for that.
Cheers

Update dependencies to run with 16.1.0

---

dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
dataset/src/main/java/org/keycloak/benchmark/dataset/ExecutorHelper.java
dataset/src/main/java/org/keycloak/benchmark/dataset/TaskManager.java

Hi,
we noticed that the dataset SPI uses some kind of nested transactions here and there (Nesting `KeycloakModelUtils.runJobInTransactionWithTimeout()` method calls). Not sure why this is the case. Sometimes when creating a big set of data we got some Exceptions related to transactions. These exceptions went away when changing to flat transactions (remove the nesting of `KeycloakModelUtils.runJobInTransactionWithTimeout()` method calls). Also it simplifies the code.
Do you know why there is nesting of this method in place? I did a few tests what happens when the outer or inner transaction fails but couldn't make sense of it. It seems that only the innermost transaction is working (or at least performs rollbacks).
Kind regards
Benjamin

Remove nested transactions

---

dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
dataset/src/main/java/org/keycloak/benchmark/dataset/RealmContext.java

We realized that the dataset spi consumes a huge amount of memory when many users and clients are created.
This may change the behaviour of the running keycloak instance and has also a negative  impact on performance while creating test data.
Since the lists are currently only used to get the item count I replaced them with a counters.
Closes #37

Reduce memory footprint when creating many users and clients.

---

benchmark/src/main/java/org/keycloak/benchmark/Config.java
benchmark/src/main/java/org/keycloak/benchmark/WorkloadModel.java
benchmark/src/main/scala/keycloak/scenario/CommonSimulation.scala

This PR adds an ability to chose the [Gatling operating mode](https://gatling.io/2018/10/gatling-3-closed-workload-model-support/).
By providing `--users-per-sec` parameter user choses the "open" workload mode.
By providing `--concurrent-users` parameter user choses the "closed" workload mode.

Ability to chose the Gatling workload mode (open/closed).

---

benchmark/src/main/java/org/keycloak/benchmark/Config.java
benchmark/src/main/scala/keycloak/scenario/CommonSimulation.scala
benchmark/src/main/scala/keycloak/scenario/_private/OIDCRegisterAndLogoutSimulation.scala
benchmark/src/main/scala/keycloak/scenario/admin/UserCrawl.scala

Replacing assertion for maximum number of failed requests with maximum request error percentage.

Replaced `maxFailedRequests` SLA assertion with `maxErrorPercentage`.

---

benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala

This fixes the behavior observed in the test. 
This now uses the correct parameter, as seen in [ClientsResouce](https://github.com/keycloak/keycloak/blob/7335abaf08915d364f16667733237aa8ac8a3b0f/services/src/main/java/org/keycloak/services/resources/admin/ClientsResource.java#L109): 
```
public Stream<ClientRepresentation> getClients(@QueryParam("clientId") String clientId,
@QueryParam("viewableOnly") @DefaultValue("false") boolean viewableOnly,
@QueryParam("search") @DefaultValue("false") boolean search,
@QueryParam("q") String searchQuery,
@QueryParam("first") Integer firstResult,
@QueryParam("max") Integer maxResults) {
```
Closes #51

Fix parameter passed to list clients endpoint

---

README.md
benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
benchmark/src/main/scala/keycloak/scenario/admin/CreateRealms.scala

A new scenario is added to perform and measure realm creation performance with Keycloak.
Command-line example for running this scenario:
```
./kcb.sh --scenario=keycloak.scenario.admin.CreateRealms \
--server-url=http://localhost:8080 \
--concurrent-users=1 \
--measurement=300 \
--realm-name=master \
--client-secret=<secret>
```
Closes #56 
*Implementation note*
Ensuring realm name and id uniqueness is achieved by adding a property containing a unique ID for each user created to execute the scenario by gatling (using the `Feeder` facility), and using this property into the realm name and id.
This Gatling user property (available from the user Session), named `gatlingUniqueUserId`, can be used elsewhere as well as this is quite generic.
*Documentation note*
When using the document process …

Add a CreateRealms scenario to measure realm creation scalability (fixes #56)

---

README.md
benchmark/pom.xml
benchmark/src/main/resources/logback.xml

* Upgraded `gatling` 3.4.0 -> 3.4.2 to include changes for https://github.com/gatling/gatling/issues/3994
* Added `janino` to enable logback conditional configuration
* Updated logback configuration file to set proper logger levels depending on Java properties
* Added a logging section into README
Closes #54

Configure HTTP logging via script arguments instead of logback.xml changes (fixes #54)

---

provision/docker-compose/PROVISION.md
provision/docker-compose/keycloak/keycloak-legacy-postgres.yml

Using docker and docker-compose add a starter docker-compose.yml to be able to bring up keycloak server and postgres db containers.
The distribution used is a wildfly legacy server application and old store configurations are in place. In addition to that we have used cpusets within the docker-compose definitions to control the cpu quota allocated to the services within these containers. 
note: In future, we would like to add another setup for newer Quarkus based keycloak distribution and new store, both together or as separate definitions. 
This PR also includes the steps to deploy the  custom provider to the containerized Keycloak server and have the possibility to create seed data efficiently.
-----------
Closes #66

Add provision module to keycloak-benchmark

---

benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala

Also checking the result so that it contains max. 2 entries.
Closes #73

Limit the number of groups and roles returned by adding the necessary query parameters

---

benchmark/BENCHMARK.md
benchmark/manage_gatling_client.sh

Implementation details:
A simple bash utility which consumes the kcadm.sh CLI script bundled with the Keycloak distributions. 
Documentation note:
Detailed instructions are update in the README for the benchmark module
Closes #75

Add a bash utility to automate the service account enabled client management steps

---

benchmark/src/main/java/org/keycloak/benchmark/Config.java
benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
benchmark/src/main/scala/keycloak/scenario/admin/JoinGroup.scala

This scenario creates a new user, finds a given group and then adds the user to that group.
It can be used to check if group assignments still perform in reasonable time frames on systems with a lot of entities (especially groups and roles).

Join group test scenario.

---

benchmark/BENCHMARK.md
benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
benchmark/src/main/scala/keycloak/scenario/admin/CreateDeleteUsers.scala
benchmark/src/main/scala/keycloak/scenario/admin/CreateUsers.scala

re-use and add new methods to support the create, read and delete operations for the User entity to test the new storage layer
closes #88 
The BENCHMARK.md has been updated to reflect the addition of the new entities

Add CREATE, DELETE, READ Operations for User Entity (closes #88)

---

provision/minikube/keycloak/templates/keycloak.yaml
provision/minikube/monitoring.yaml
provision/minikube/promtail.yaml
provision/minikube/upgrade.sh

With the latest OTEL 1.15 java agent release, the [JBoss JSON logger will log the trace IDs](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6112). 
After upgrading and updating the configuration, the logs now link to the traces, traces link to the logs, and logs can be filtered by the trace id.

Upgrading OTEL agent, parsing traceIds and linking traces to logs

---

provision/minikube/monitoring.yaml

Prometheus metrics can contain a trace ID for a metric that links to a recorded trace. More information are available in this blog post: https://vbehar.medium.com/using-prometheus-exemplars-to-jump-from-metrics-to-traces-in-grafana-249e721d4192
With the current open telemetry setup, this is available for the metric `http_server_duration_bucket`.
This commit enables this. 
An example query is: 
> histogram_quantile(0.95, sum(rate(http_server_duration_bucket [1m])) without (pod,http_host, http_flavor, job,endpoint, instance)) 
This works for timeseries diagrams when exemplars are enabled in the query:
(1) enable exemplars in the query
(2) hover with the mouse over an exemplar in the diagram, shown as a small rhombus
(3) click on the "Query with Jaeger" link to open a trace that matches the …

Enable exemplars for Prometheus and Grafana timeseries diagrams.

---

provision/minikube/monitoring/dashboards/keycloak-perf-tests.json

Closes #105
- Add rate to the GC metrics under the Keycloak - JVM Stats
- Modify the label of the connection pool metrics
- consume the newly created pg_locks_waiting_count to display, total number of locks in waiting state instead of the total locks

Improve the keycloak-perf-tests grafana dashboard in the minikube setup (fixes #105)

---

benchmark/BENCHMARK.md
benchmark/generate-custom-report.sh
benchmark/src/main/resources/diff-v2.mustache

- Utility downloads the needed binary. 
- Generates the report taking the source simulation logs and a target report directory and writes the HTML|CSV report there. 
- In the end, it removes the binaries. 
- The utility can also optionally consume a custom mustache template used to customize the reports, which is currently hosted under benchmark/src/main/resources.
Documentation note:
Updated the Report section of the benchmark/BENCHMARK.md with the new utility usage information.
Closes #100

Adding Utility to create custom reports (fixes #100)

---

benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala

This makes the "/auth" prefix optional.
In order to test it with the minikube setup, I needed to manually:
* enable user self-registration in `realm-0`
* created a client "client-0" with a valid redirect URL - I chose "https://keycloak.xxx.xxx.xxx.xxx.nip.io/*" (replace with the the current IP address)
* created a "user-0" with a password "user-0-password"
I wonder if this could be automated more using dataset provider or the shell script or a mixture of both.
Closes #122

Fix URL pattern for Quarkus distribution

---

kcb-ci-runner.sh

This script assumes, it will intake certain environment and parametrized variables coming in from a CI system job (ex. Jenkins)
The script automates a bunch of actions needed, such as
- Reset the Keycloak K8s setup using minikube
- SET all the needed environment variables and configurations for the simulation and execute the simulation
- Archive the Gatling results, create the custom report and store all the Archived resutls, reports in a central location

Add a Keycloak Benchmark CI runner script, to execute simulations on a CI System (fixes #134)

---

provision/minikube/README.adoc
provision/minikube/Taskfile.yaml
provision/minikube/keycloak/templates/keycloak.yaml
provision/minikube/keycloak/values.yaml

Closes #138
The provisioning of Keycloak will succeed, but then fail with an error when setting up the Gatling client: https://github.com/keycloak/keycloak/issues/13200
I assume that this PR can be reviewed and merged regardless, as it looks independent to the Keycloak issue. 
To run the provisioning with a given storage option, execute
```
task KC_STORAGE=jpa
```
Another supported value is `chm` for concurrent hashmap. Eventually we would also run tests for that. As of tomorrow the nightly build will contain also the user-session storage.

Adding the storage option to the provisioning

---

provision/minikube/keycloak/templates/NOTES.txt
provision/minikube/keycloak/templates/infinispan/infinispan-deployment.yaml
provision/minikube/keycloak/templates/infinispan/infinispan-ingress.yaml
provision/minikube/keycloak/templates/infinispan/infinispan-nodeport.yaml
provision/minikube/keycloak/templates/infinispan/infinispan-service.yaml
provision/minikube/keycloak/templates/keycloak.yaml

Closes #168
@ahus1 @kami619 I was able to fix the problem with health checks. It was caused by the fact that we added:
```
- name: db
value: postgres
```
even when Infinispan is used. I changed the condition to not include it and it works now.

Add Infinispan to minikube setup

---

benchmark/initialize-benchmark-entities.sh
dataset/dataset-import.sh
doc/benchmark/modules/ROOT/pages/preparing-keycloak.adoc
doc/benchmark/modules/ROOT/pages/run/running-benchmark-cli.adoc
doc/benchmark/modules/ROOT/pages/scenario/authorization-code.adoc
provision/minikube/Taskfile.yaml

- Renaming the manage-gatling-client.sh to initialize-benchmark-entities.sh
- Adding new user creation capabilities to the script to create a default user to be able to kick off a single user Authentication scenarios (LoginUserPassword, ClientSecret, AuthorizationCode)
- The `initialize-benchmark-entities.sh` new oidc type client called `client-0` to support Authentication style scenarios and non-intersecting with the Service Enabled Client
- Updating the docs to reflect the latest state

Adding new capabilities to initialize-benchmark-entities.sh (fixes #159)

---

provision/minikube/rebuild.sh

Freezes the kubernetes version to 1.24 until activity #211 is complete.

Allows you to provision the environment in version 1.27 of minikube

---

benchmark/src/main/content/bin/kcb.sh

This avoids blanks in parameters to split them.
Closes #204

Using an array when generating the CLI options for the downstream script

---

provision/minikube/monitoring/dashboards/keycloak-perf-tests.json

created a widget to track the 5m rate of the  write, read and total IOPS with min,max,current,mean values plotted by each container
Sample screen grab of the widgets
------------------------------------------------------
Closes #197

Add new DB IOPS widgets to the keycloak-perf-tests grafana dashboard (Closes #197)

---

benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala

handle additional forward slashes in the server url config value by stripping the suffix of the stored serverUrl scala variable
-----
Closes #229

handle additional forward slashes in the server url config value (fixes #229)

---

dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java

Context: Even though we fixed the redirect_uri used for logouts after a breaking change, we only did the change in the initialize_benchmark_entities.sh script and subsequent clients it would create. However, we would need this change also in the dataset module, so that, any clients which are created at scale would also work without issue.
As part of it, I have re-used the pattern from this PR [commit](https://github.com/keycloak/keycloak/commit/c00514d659f4b7416abecf35d1abb4f959675ee4#diff-e0e8f2c00bda6b7c51673acec8bac747f21b36c4dace3eaabcd6b3b7feee2043R122-R124) from Keycloak repository
- set the client with 'post.logout.redirect.uris' attribute and value '+' if logout redirect uris are set to null
@ahus1 I have generated a dataset module with this change and the logout api performed by …

extend the fix around redirect_uri to dataset module

---

doc/kubernetes/modules/ROOT/pages/util/sqlpad.adoc
provision/minikube/keycloak/templates/sqlpad.yaml

Expose the SQLPAD_QUERY_RESULT_MAX_ROWS configuration variable to be able to configure max rows displayed as a result of a query
Fixes #254

Expose the SQLPAD_QUERY_RESULT_MAX_ROWS in sqlpad app

---

doc/benchmark/modules/ROOT/pages/preparing-keycloak.adoc
doc/benchmark/modules/ROOT/pages/run/running-benchmark-cli.adoc

* Scripted configuration uses the auth in the server url http://localhost:8081/auth due to which it fails with 
`Logging into http://keycloak.minikubeIp.nip.io/auth as user admin of realm master
null [RESTEASY003210: Could not find resource for full path: http://keycloak.192.168.64.17.nip.io/auth/realms/master/protocol/openid-connect/token]`
* Making the server url more realistic as it uses  http://keycloak.minikubeIp.nip.io instead of localhost
* Specifying KEYCLOAK_HOME is never mentioned in the guide

Updating the Preparing Keycloak guide

---

doc/kubernetes/modules/ROOT/pages/util/custom-image-for-keycloak.adoc
pom.xml
provision/minikube/Taskfile.yaml

Changes the default version string from `999-SNAPSHOT` to `999.0.0-SNAPSHOT`. This makes it a valid version under the [Semantic Versioning](https://semver.org/) standard.
The motivation for this change is to make versioning interoperable between Maven and NPM, as the latter only allows for Semantic Versioning. This allows for simplification in the release process, as we no longer need to convert version numbers from one to the other.
For more information see https://github.com/keycloak/keycloak/issues/17335.

Use a valid SemVer format for the SNAPSHOT version

---

doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
provision/minikube/Taskfile.yaml

Added an option for setting a custom version of the Keycloak Operator:
`KC_OPERATOR_TAG` - defaults to `nightly`

Add support for setting a custom version of the Keycloak Operator

---

doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
provision/minikube/Taskfile.yaml
provision/minikube/keycloak/templates/keycloak.yaml
provision/minikube/keycloak/values.yaml

Added support for the following options:
`KC_INSTANCES` - number of KC instances
`KC_CPU_REQUESTS` - minimum cores per KC pod, defaults to `0`
`KC_CPU_LIMITS` - maximum cores per KC pod, defaults to `1`
`KC_MEMORY_REQUESTS_MB` - minimum memory per KC pod in MB, defaults to `1024`
`KC_MEMORY_LIMITS_MB` - maximum memory per KC pod in MB, defaults to `1024`
`KC_HEAP_INIT_MB` - initial heap space size
`KC_HEAP_MAX_MB` - max heap space size
`KC_METASPACE_INIT_MB` - initial meta space size
`KC_METASPACE_MAX_MB` - max meta space size

Add support for Keycloak scaling and setting resource limits

---

.github/workflows/provision-minikube.yml
doc/kubernetes/modules/ROOT/nav.adoc
doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
doc/kubernetes/modules/ROOT/pages/error-messages.adoc
doc/kubernetes/modules/ROOT/pages/storage-configurations.adoc
doc/kubernetes/modules/ROOT/pages/storage/infinispan.adoc
doc/kubernetes/modules/ROOT/pages/storage/postgres-infinispan.adoc
provision/minikube/Taskfile.yaml
provision/minikube/keycloak/templates/infinispan/infinispan-deployment.yaml
provision/minikube/keycloak/templates/infinispan/infinispan-ingress.yaml
provision/minikube/keycloak/templates/infinispan/infinispan-nodeport.yaml
provision/minikube/keycloak/templates/infinispan/infinispan-service.yaml
provision/minikube/keycloak/templates/keycloak.yaml
provision/minikube/keycloak/templates/postgres/postgres-deployment.yaml
provision/minikube/keycloak/templates/postgres/postgres-exporter-configmap.yaml
provision/minikube/keycloak/templates/postgres/postgres-exporter.yaml
provision/minikube/keycloak/templates/postgres/postgres-nodeport.yaml
provision/minikube/keycloak/templates/postgres/postgres-service.yaml
provision/minikube/keycloak/templates/sqlpad.yaml

This introduces a mixed setup that mirrors what we have in the Legacy store: auth sessions, user sessions, login failures, and single use objects in hotrod, rest on JPA.
For documentation purposes, I'm adding some info about changes we had to make to be able to run this scenario.
1- In the postgres deployment, we've added an arg to enable prepared transactions, which are disabled by default. This is required by Arjuna when it is attempting to coordinate the transactions involving the two stores. So this change:
```
args:
- -c
- max_prepared_transactions=100
```
prevents the Arjuna exception:
```
2023-03-22 09:54:22,744 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-6) Uncaught server error: java.lang.RuntimeException: javax.transaction.HeuristicMixedException
at …
```

Add "mixed" (JPA/HotRod) storage setup

---

doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
doc/kubernetes/modules/ROOT/pages/installation.adoc
doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-java.adoc
doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-minikube.adoc
doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-yq.adoc
provision/minikube/Taskfile.yaml
provision/minikube/keycloak/values.yaml
provision/minikube/rebuild.sh

- Updated https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/prerequisite/prerequisite-minikube with a Linux section explaining that KVM2 is necessary, explained how to set it up for a Linux host OS and a small check to verify that.
- Java is added as a prerequisite https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/installation, with steps for installation of OpenJDK and create a JAVA_HOME variable for specific JDK version and step to verify if the installation was successful.
Additionally added couple of checks to ensure the host is vetted for
- Virtualization and the user is associated with the libvirt group
- Validate if JAVA_HOME variable is set properly
-----
Fixes #300

updating docs to support kvm2 and java as pre-req installations

---

doc/kubernetes/modules/ROOT/pages/openshift.adoc
provision/common/Taskfile.yaml
provision/minikube/Taskfile.yaml
provision/openshift/Taskfile.yaml

Fixes #314 
- Added the support to create the needed service account enabled client, test-realm and users to start a benchmark against the Openshift cluster based Keycloak instance.
- Akin to the above point, to be able to deploy dataset module to the Openshift cluster based Keycloak instance and create needed datasets for various entities.
Even though the dataset module is ported, I am observing an issue @ahus1 with the keycloak/providers directory unable to be mounted to `/opt/keycloak/providers` thus not able to run the dataset-import.sh script to create the entities, I might need some help on this.

Porting changes for supporting Dataset and Gatling User entities creation on OCP

---

provision/openshift/Taskfile.yaml

While working on the namespace customization I needed to pass the `KC_NAMESPACE_PREFIX` property to `isup.sh` script. I tried to use export in the `keycloak` task, however, it didn't work, and then I forgot to remove it.
This Pr is to remove it.

Remove unnecessary exports

---

provision/openshift/Taskfile.yaml

Incorrect dir while referencing the operator-patch.yaml is corrected
Closes #331

Corrects the incorrect reference to a resource when using custom keycloak image (Fixes #331)

---

.github/actions/rosa-cli-setup/action.yml
.github/workflows/rosa-cluster-create.yml
.github/workflows/rosa-cluster-delete.yml
provision/aws/rosa_create_cluster.sh
provision/aws/rosa_delete_cluster.sh
provision/aws/rosa_recreate_admin.sh

I've tested this on my fork:
* Create cluster: https://github.com/stianst/keycloak-benchmark/actions/runs/5088576833/jobs/9145155404
* Delete cluster: https://github.com/stianst/keycloak-benchmark/actions/runs/5088530163/jobs/9145048362

Add GitHub workflows to create and delete a shared ROSA cluster

---

.github/workflows/README.md
.github/workflows/rosa-cluster-auto-delete-on-schedule.yml
.github/workflows/rosa-cluster-auto-provision-on-schedule.yml
.github/workflows/rosa-cluster-delete.yml
provision/aws/rosa_cluster_reaper.sh
provision/openshift/Taskfile.yaml

Adding two new workflow files:
- rosa-cluster-auto-provision-on-schedule
- rosa-cluster-auto-delete-on-schedule
Setting static values for cluster creation, as below:
- CLUSTER_NAME: shared-crossdc
- COMPUTE_MACHINE_TYPE: m5.xlarge
- MULTI_AZ: false
- REPLICAS: 2
and a Rosa cluster reaper scripts, which takes input of a list of "ready" state clusters
- rosa_cluster_reaper.sh
My first attempt at GH workflow's so if something's amiss, please correct it :) 
Open question, there could be cluster's which could be in other `states` other than `ready`, do we want any alert on it ? Another question is, do we want any email notification after the job is complete, alternative would be to personally tune the GH Workflow notifications to report on this workflow, reducing the email clutter.

Automated scheduling of creation of shared ROSA cluster and another end of business reaper 

---

.github/actions/get-keycloak-url/action.yml
.github/actions/keycloak-create-dataset/action.yml
.github/actions/keycloak-create-deployment/action.yml
.github/actions/keycloak-delete-deployment/action.yml
.github/actions/oc-keycloak-login/action.yml
.github/workflows/README.md
.github/workflows/keycloak-create-dataset.yml
.github/workflows/keycloak-create-deployment.yml
.github/workflows/keycloak-delete-deployment.yml
.github/workflows/keycloak-incremental-client-credentials-benchmark.yml
.github/workflows/keycloak-scalability-benchmark.yml
.github/workflows/rosa-run-benchmark.yml
benchmark/src/main/content/bin/kcb.sh
doc/benchmark/modules/ROOT/pages/configuration.adoc
doc/benchmark/modules/ROOT/pages/kcb-modes.adoc
doc/benchmark/modules/ROOT/pages/release.adoc
doc/benchmark/modules/ROOT/pages/run/running-benchmark-cli.adoc
doc/kubernetes/modules/ROOT/pages/customizing-deployment.adoc
doc/kubernetes/modules/ROOT/pages/installation-openshift.adoc
provision/aws/rosa_cluster_reaper.sh

Closes #354 
Closes #355
@kami619 Do we want to add also user scenario within this PR, or we will do it as a follow-up?

Introduce incremental workflow scenarios to GHA

---

doc/kubernetes/modules/ROOT/pages/installation-openshift.adoc
provision/minikube/keycloak/templates/NOTES.txt
provision/minikube/keycloak/templates/cockroach-operator/cockroach-nodeport.yaml
provision/minikube/keycloak/templates/cockroach-single/cockroach-nodeport.yaml
provision/minikube/keycloak/templates/infinispan/infinispan-nodeport.yaml
provision/minikube/keycloak/templates/keycloak-jvmdebug-service.yaml
provision/minikube/keycloak/templates/postgres/postgres-nodeport.yaml
provision/minikube/keycloak/values.yaml
provision/openshift/Taskfile.yaml

This simplifies the installation of multiple Keycloak installations in a shared OpenShift cluster.
As those ports are AFAIK not accessible from outside of the cluster in the current setup, they are not very useful anyway.

Avoid node-ports usage in OpenShift

---

provision/minikube/Taskfile.yaml

"minikube ssh" stopped to work on Fedora / lead to a timeout, while direct ssh still works.
Reason unknown, `ssh docker@$(minikube ip) -i $(minikube ssh-key) -o StrictHostKeyChecking=no ...` for the rescue.

Workaround for "minikube ssh" running into a timeout

---

provision/minikube/monitoring/dashboards/keycloak-perf-tests.json
provision/openshift/monitoring/dashboards/keycloak-perf-tests.json

Updated both minikube and openshift provisioning dashboards for keycloak-perf-tests to contain new JVM information and JVM widgets which can help with profiling and analysis of a benchmark run.
--------
Fixes #364

Additional JVM widgets in Grafana dashboard

---

.github/actions/keycloak-create-deployment/action.yml
provision/common/Taskfile.yaml
provision/minikube/keycloak/templates/keycloak.yaml
provision/minikube/keycloak/templates/otel-pvc.yaml
provision/minikube/monitoring/dashboards/client-credentials-otel.json
provision/minikube/monitoring/dashboards/keycloak-infinispan.json
provision/openshift/monitoring/dashboards/client-credentials-otel.json

Relates to #372
WIP - works only with 1 pod at the moment due to PVC access mode
Board with example data (15 minutes run of client credential grant with 100_000 clients and 10_000 clients-per-realm and 10 concurrent users):

Make otel work with Openshift and add Grafana dashboard

---

.github/workflows/keycloak-chaos-benchmark.yml
benchmark/src/main/content/bin/kc-chaos.sh
benchmark/src/main/content/bin/kcb.sh
doc/benchmark/modules/ROOT/pages/kcb-modes.adoc
doc/kubernetes/modules/ROOT/pages/util/kc-chaos.adoc

fixes #393 
Client Secret Failure run -https://github.com/kami619/keycloak-benchmark/actions/runs/5402389905/jobs/9813602924
Auth Code Failure run - https://github.com/kami619/keycloak-benchmark/actions/runs/5404050859/jobs/9817708034
----
co-author : @mhajas

updates for optimizing failure scenario

---

ansible/roles/benchmark/tasks/install.yml

Replaced hard-coded `ec2-user` with dynamic Ansible value `{{ ansible_ssh_user }}`.

Fix user permissions in the `benchmark` Ansible role.

---

provision/aws/rosa_create_cluster.sh

When we use spot instances sometimes a worker node is removed and all pods running on that node are deleted. This can result in removing more than 1 pod, which means we are losing some sessions. This is something we cannot afford in our scalability testing, therefore removing the switch. 
I am running Keycloak with 600k user sessions at the moment with regular instances (no spot), and everything works well while with spot instances there were regular pod restarts.

Do not use spot instances

---

provision/minikube/Taskfile.yaml
provision/minikube/isup.sh
provision/openshift/isup.sh

Closes #428 .
Additionally, enabled passing of the `KC_CRYOSTAT` flag in `provisioning/minikube/Taskfile.yaml`.

Skip waiting for Cryostat service when `KC_CRYOSTAT` is set to `false`.

---

provision/minikube/monitoring/dashboards/keycloak-infinispan.json

This adds some new metrics to ISPN dashboard. This is how it looks like now:

Update ISPN dashboard with JGroups metrics

---

ansible/roles/aws_ec2/defaults/main.yml
ansible/roles/aws_ec2/tasks/create-resources.yml
ansible/roles/aws_ec2/tasks/manage-instances.yml

Security sensitive data like key pairs, IPs, etc. are now hidden from Ansible logs by default.
For debugging purposes these logs can be explicitly enabled by setting the Ansible variable `no_log_sensitive` to `false`.
Closes #435

Hide security-sensitive data from Ansible logs.

---

provision/minikube/monitoring/dashboards/keycloak-perf-tests.json
provision/openshift/monitoring/dashboards/keycloak-perf-tests.json

Add new widget to Openshift grafana dashboard for CPU throttling
Fix couple of widget names to match to the data they represent
Note: I backported the fixes for widget names but couldn't test the new widget on Minikube as my local minikube setup is having some trouble, will backport the CPU throttling widget as soon as fix my local minikube.

add CPU throttling widget in openshift dashboard

---

doc/benchmark/modules/ROOT/nav.adoc
doc/benchmark/modules/ROOT/pages/report/rosa-benchmark-key-results.adoc

Add ROSA Benchmark Key Results

---

provision/minikube/keycloak/config/kcb-infinispan-cache-config.xml
provision/minikube/keycloak/config/kcb-infinispan-cache-remote-store-config.xml
provision/minikube/keycloak/templates/keycloak.yaml

Adding FD_SOCK2 -> FD_SOCK workaround

---

.github/workflows/aurora-cluster-auto-delete-on-schedule.yml

The reaper is failing with:
```
/home/runner/work/_temp/c0ca7b2b-7d9b-46f9-840d-25903c252923.sh: line 1: ./provision/aws/rds/aurora_cluster_reaper.sh: No such file or directory
```
This is because the code has not been checked out.

Add missing checkout step to Aurora reaper

---

ansible/roles/benchmark/tasks/run.yml
doc/benchmark/modules/ROOT/pages/run/running-benchmark-ansible.adoc

This should help when the SSH connection is unstable. 
When running it this way, there are a lot of additional log messages for the polling - I hope you don't mind.
It also catches the problem automatically which was previous only documented, but not enforced.

Refine Ansible playbook with max users per node and async execution

---

provision/infinispan/README.adoc
provision/infinispan/Utils.yaml
provision/infinispan/ispn-helm/identities.yaml
provision/infinispan/ispn-helm/templates/infinispan.yaml
provision/infinispan/ispn-helm/values.yaml
provision/minikube/keycloak/values.yaml
provision/openshift/Taskfile.yaml

2 changes included in the PR:
* Removed `KC_ISPN_PORT` since it is not possible to change it. 
* Static password (shared password) set for the Hot Rod Endpoint

Use static password in the Hot Rod endpoint

---

.github/actions/ec2-create-instances/action.yml
.github/actions/ec2-delete-instances/action.yml
.github/actions/keycloak-create-dataset/action.yml
.github/actions/keycloak-create-deployment/action.yml
.github/workflows/rosa-scaling-benchmark.yml
ansible/aws_ec2.sh
ansible/benchmark.sh
ansible/env_rosa_benchmark.yml
ansible/roles/aws_ec2/defaults/main.yml
ansible/roles/aws_ec2/tasks/create-resources.yml
ansible/roles/aws_ec2/tasks/main.yml
doc/benchmark/modules/ROOT/pages/report/rosa-benchmark-key-results.adoc

Automation of Rosa Scaling Benchmark (#444): Part 1

---

.github/workflows/rosa-cluster-create.yml
doc/kubernetes/modules/ROOT/nav.adoc
doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-rosa.adoc
doc/kubernetes/modules/ROOT/pages/storage/aurora-postgres.adoc
provision/aws/rds/aurora_create_peering_connection.sh
provision/aws/rds/aurora_delete_peering_connection.sh
provision/aws/rosa_create_cluster.sh

It's necessary for each ROSA cluster to use a non-overlapping
machine-cidr range when deploying across multiple AWS regions. If the
cidr range overlaps, then Aurora DB responses will not be correctly
routed to cluster than initiated a request.
Resolves https://github.com/keycloak/keycloak-benchmark/issues/467
@ahus1 @mhajas Utilising VPC peering connections to limit DB accessibility is the way to go when deploying production systems, but I'm starting to think it might be getting too restrictive for benchmarking with many clusters. If this continues be a pain point, I think we should consider documenting the steps required for said setup and then simply revert to using Aurora endpoints exposed over the internet.

Aurora multi region

---

provision/infinispan/Utils.yaml

Resolves #482
So... a lot of small changes:
* The main one, `rosa-oc-login` now checks for the ROSA cluster id and re-authenticates if it is different. 
* Added `label:` to all shared tasks to help with the output.
* `rosa-oc-login` now fetches the OCP DNS prefix and the OCP API URL
* Renamed some variables

Improve rosa-oc-login subtask to detect new cluster

---

provision/infinispan/ispn-helm/templates/infinispan.yaml

This is a quick and easy way for us to make the external metric names align with the embedded infinispan names. A better solution would be to explicitly set the JGroups cluster name in the Keycloak EmbeddedCacheManager to a meaningful name associated with a specific Keycloak instance. I'll discuss this with the team and contribute a Keycloak PR as required.
Relates to: https://github.com/keycloak/keycloak-benchmark/issues/464

Hardcode JGroups cluster name to match Keycloak embedded settings

---

dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java
doc/dataset/modules/ROOT/pages/using-provider.adoc

This PR creates hierarchical groups using the configuration parameters: groups-count-each-level, groups-hierarchy-depth, groups-with-hierarchy.  Boolean parameter groups-with-hierarchy is "false" by default. With the default values it works as before. 
With groups-with-hierarchy=true, it ignores groups-per-realm parameter and creates the group tree structure as defined by the other parameters. This will be groups-count-each-level ^ groups-hierarchy-depth. 
The implementation honors groups-per-transaction.
We adopted a subgroup naming convention that uses "." in the group names which allows finding the parent group even if it was created in a previous transaction.
Closes #471

Ciam 6580 issue 471 hiearchical groups

---

provision/minikube/monitoring/dashboards/keycloak-perf-tests.json
provision/openshift/monitoring/dashboards/keycloak-perf-tests.json

applied to both minikube and OpenShift deployments and they seem to work as excepted now, even when there are multiple Keycloak namespaces deployed to the same K8s cluster

fix the missing namespace in widget filters for PostgreSQL DB widgets

---

provision/minikube/monitoring/dashboards/keycloak-infinispan.json

Closes #464
This PR adds ability to reuse Keycloak Infinispan Grafana board for external infinispan. To switch to the external infinispan, just select the correct namespace. 
Stats for local caches are empty for external Infinispan as there are no local caches.

Dashboard for external Infinispan metrics

---

.github/actions/keycloak-create-dataset/action.yml
.github/actions/prometheus-metrics-calc/action.yml
.github/actions/prometheus-run-queries/action.yml
.github/workflows/rosa-scaling-benchmark.yml
doc/benchmark/modules/ROOT/pages/report/rosa-benchmark-key-results.adoc

PR contains:
1) Created 2 new actions for performing prometheus queries and calculating/storing result numbers into JSON file;
2) besides the result json file I am publishing the intermediate files with metric numbers before /after benchmark execution, for being able to debug the correctness of numbers before merging the PR;
3) I have added "continue-on-error": true to benchmark execution steps, as sometimes Gatling gives failure during report generation (if some of conditions doesn't met) and the whole workflow fails, even though the metrics can be taken and can be calculated
4) fixed if conditions on action steps as the steps were working no matter if condition was met or not;
The workflow execution for 5 minutes gives the following JSON:
```
{
"Testing memory for creating sessions": { …
```

Automation of Rosa Scaling Benchmark (#444): Part 2

---

ansible/roles/benchmark/tasks/run.yml

This fixes `MemoryError` errors encountered when transferring large files from the remote EC2 instances.
https://stackoverflow.com/questions/41367278/how-to-fix-memory-error-in-ansible

Use synchronize instead of ansible fetch

---

benchmark/src/main/content/bin/kcb.sh

A bit hacky, but it works. Don't know a better way to do it since Gatling is what prints the statement.

Replace file: /path, with file:///path, to make it a clickable link in bash

---

provision/minikube/keycloak/config/kcb-infinispan-cache-remote-store-config.xml
provision/minikube/keycloak/templates/keycloak.yaml
provision/rosa-cross-dc/Taskfile.yaml

* Added 'jboss.site.name' property
* Removed 'site' attribute from Infinispan configuration
Need to test it in Openshift but I'm expecting to see a log entry like: `[org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: pedro-desktop-30198, Site name: my-site` with the proper site's name.
I saw usage of the site name in the events triggered by the work cache and some sessions/login failures cache.

Configure site name in Keycloak

---

provision/infinispan/Utils.yaml
provision/infinispan/ispn-helm/templates/infinispan.yaml
provision/infinispan/ispn-helm/values.yaml

Defaults: 10 sec with 2 sec heartbeat interval (suspected after 5 heartbeats lost)
Fixes #532

Make Infinispan failure detection timeout configurable

---

benchmark/src/main/java/org/keycloak/benchmark/Config.java
benchmark/src/main/scala/keycloak/scenario/CommonSimulation.scala
benchmark/src/main/scala/keycloak/scenario/KeycloakScenarioBuilder.scala
doc/benchmark/modules/ROOT/pages/configuration.adoc
doc/benchmark/modules/ROOT/pages/scenario/authorization-code.adoc

- Updated the Refresh Token scenario to optionally use `"Connection": "close"` for the refresh token endpoint
- Also adding a new way to look at the http requests sent using external proxy client with `--http-proxy` cli argument
fixes #518

close http connections explicitly

---

provision/minikube/keycloak/templates/keycloak.yaml

With https://github.com/keycloak/keycloak/issues/22109 not being available, I wonder if we should disable those tests by default.

Disable liveness and readiness probes to handle high load

---

.gitignore
ansible/benchmark.sh
benchmark/src/main/content/bin/kcb.sh
benchmark/src/main/python/requirements.txt
benchmark/src/main/python/snapGrafana.py
doc/kubernetes/modules/ROOT/pages/util/grafana.adoc

basic python script to generate PDFs of the dashboards

---

.github/workflows/keycloak-scalability-benchmark.yml
.github/workflows/rosa-scaling-benchmark.yml
doc/benchmark/modules/ROOT/pages/report/rosa-benchmark-key-results.adoc
doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-rosa.adoc

There was a change in ROSA that does not allow creating machine pools with max-replicas set to 0. https://github.com/keycloak/keycloak-benchmark/pull/556 updated `rosa_create_cluster` script, however, we need to update also other occurrences of max-replicas.

Update machinepool manipulation based on the latest changes in ROSA

---

doc/kubernetes/modules/ROOT/pages/running/concepts/threads.adoc

Fixes #553 
@ahus1 looks like the first two points in the ticket are already [updated](https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/running/concepts/threads#jgroup-connection-pool) and let me know if they need to be elaborated any further. 
> - the reduction of Keycloak worker threads to be aligned with the JGroup thread size, as running into retries due to missing threads would still slow down the system
> - setting -Djgroups.thread_dumps_threshold=1 to get notified in the logs when the thread pool is exhausted.
I have added a new paragraph for this below item.
> monitoring the metric vendor_jgroups_tcp_get_thread_pool_size

updating the jgroups docs for kc22

---

doc/kubernetes/modules/ROOT/pages/running/keycloak-with-external-infinispan.adoc
provision/minikube/keycloak/config/kcb-infinispan-cache-remote-store-config.xml

This re-enables the state transfer even if the remote store is enabled. 
There are some situations when listing user sessions for example in InfinispanUserSessionProvider where cache loaders are skipped, so all entries should be in the cache for this case. The state transfer ensures that this is the case when a node joins or leaves. 
https://github.com/keycloak/keycloak/blob/c036980c3759b833d98030cf1299297a7ec97436/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java#L396-L397

Enable state transfer even if a remote cache is enabled

---

provision/infinispan/Utils.yaml

This aligns the scripted deployment with the deployment outlined in the documentation prepared for users.

Enable Gossip Router deployment in all sites

---

provision/aws/rds/aurora_delete.sh

Resolves issue #643.
Signed-off-by:Tomas Kyjovsky <tkyjovsk@redhat.com>

Add `--db-cluster-identifier ${AURORA_CLUSTER}` param to the `aws rds describe-db-clusters` command.

---

.github/workflows/rosa-cluster-create.yml

We are ending up in a race condition sometimes when the artifact upload for the `a` and `b` clusters is happening in conflict with the same directory name `rosa-logs`. This PR should aim to fix that, please review and merge if this looks like a viable option.
Below are the runs where I have seen this issue.
https://github.com/keycloak/keycloak-benchmark/actions/runs/7245204913/attempts/1
https://github.com/keycloak/keycloak-benchmark/actions/runs/7245204913/attempts/2

generate cluster name based rosa logs zip dir

---

.github/workflows/rosa-cluster-create.yml

fixes #625 
This needed a pre-requisite account roles to be updated to the compatible version on the account which I documented with the parent ticket - https://github.com/keycloak/keycloak-benchmark/issues/625#issuecomment-1862121549
**create rosa cluster job:**
https://github.com/kami619/keycloak-benchmark/actions/runs/7246748671 (this run was failing due to a known issue with logging operator)
https://github.com/kami619/keycloak-benchmark/actions/runs/7257494773/job/19771394191 (this run where the logging operator was working against the `4.14.5` cluster)
**delete cluster job:**
https://github.com/kami619/keycloak-benchmark/actions/runs/7257510642

upgrade to ocp 4.14.5

---

doc/kubernetes/modules/ROOT/pages/util/custom-image-for-keycloak.adoc

I suppose this is simple enough so one wouldn't need an external registry. 
Once we also build the operator, this would be a similar procedure. When building the Operator as well (to match a Keycloak release), only putting the Operator into an external registry alone doesn't solve the problem of also storing the CRD, which depends on the version of the Operator, so using an external registry doesn't solve much on its own for an OpenShit and Operator deployment.

Document oc binary build for OpenShift

---

provision/infinispan/install_operator.sh

Not recommended in production since the port is not secure and allows to observe and manipulate JGroups protocols/attributes

Enable JGroups Diagnostics

---

benchmark/src/main/python/snapGrafana.py
provision/infinispan/Utils.yaml
provision/infinispan/ispn-helm/templates/infinispan.yaml
provision/infinispan/ispn-helm/values.yaml

Fine tunning timeouts in Infinispan and JGroups
* Tunnel Heartbeats timeout must be lower than Infinispan cross-site timeout to allow the offline gossip router to be detected and retransmissions to be forwarded to the online gossip router without timing out the write operation at Infinispan
* Failure detection timeout must be higher than Tunnel heartbeat timeout to prevent a node from being suspected in case a gossip router is down
* Reduce timeout in Infinispan server to prevent Keycloak timeouts; although, I'm not sure if it is a good idea or not at this point. 
Edit: fixed the grafana snapshot python script to use HTTPS instead of HTTP.

Fine tune Infinispan timeouts

---

provision/minikube/keycloak/templates/certmanager/certmanager-jgroups-tls.yaml
provision/minikube/keycloak/templates/keycloak.yaml
provision/minikube/keycloak/values.yaml
provision/openshift/Taskfile.yaml
provision/rosa-cross-dc/Taskfile.yaml

Related to: keycloak/keycloak#25703
Until the PR listed above is merged and the code is available in a nightly build, a locally built image will need to be used.

Use JGroups MTLS setup with certmanager generated certificates

---

provision/minikube/keycloak/templates/keycloak.yaml

As per the recent changes in Keycloak https://github.com/keycloak/keycloak/issues/26455 we need to consume the same in the keycloak-benchmark deployments.

Use `http-pool-max-threads` instead of `QUARKUS_THREAD_POOL_MAX_THREADS`

---

doc/kubernetes/modules/ROOT/pages/openshift/cross-site-rosa.adoc
provision/keycloak-tasks/Taskfile.yaml
provision/keycloak-tasks/Utils.yaml
provision/keycloak-tasks/keycloak-image-helm/templates/keycloak-build-config.yaml
provision/keycloak-tasks/keycloak-image-helm/templates/keycloak-nightly-imagestream.yaml
provision/keycloak-tasks/keycloak-image-helm/templates/keycloak-operator-build-config.yaml
provision/keycloak-tasks/keycloak-image-helm/templates/keycloak-with-AWS-JDBC-wrapper.yaml
provision/keycloak-tasks/keycloak-image-helm/values.yaml
provision/minikube/keycloak/templates/aurora/aurora-service.yaml
provision/minikube/keycloak/templates/keycloak.yaml
provision/minikube/keycloak/values.yaml
provision/rosa-cross-dc/Taskfile.yaml

Closes #698
This is WIP PR to use the AWS JDBC wrapper for. 
Checklist:
I am testing this from `keycloak-tasks` directory with the following `.env` file:
```
KC_INSTANCES=1
KC_HOSTNAME_SUFFIX=<cluster-hostname-suffix>
ROSA_CLUSTER_NAME=gh-keycloak-a
KUBECONFIG=/path/to/kubeconfig
NAMESPACE=mhajas-keycloak
```

Add possibility to configure AWS JDBC Wrapper for Keycloak driver

---

provision/aws/route53/route53_delete.sh

It seems CloudWatch alarms and SNS topics are not cleaned correctly by the nightly run. There is the following error in the output logs:
```
An error occurred (ValidationException) when calling the DeleteFunction operation: 2 validation errors detected: Value '{"Id":"03a282bd-4954-4c9d-a950-29cef7d682d4","CallerReference":"d54738171435725144e3d2ed900ec890c7b1d04d","HealthCheckConfig":{"Port":443,"Type":"HTTPS","ResourcePath":"/lb-check","FullyQualifiedDomainName":"primary.gh-keycloak-a-gh-keycloak-b-mtq5mtkk.keycloak-benchmark.com","RequestInterval":30,"FailureThreshold":1,"MeasureLatency":false,"Inverted":false,"Disabled":false,"EnableSNI":true},"HealthCheckVersion":6}' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: …
```

Fix cleaning up of the failover lambda

---

dataset/dataset-import.sh
dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java
dataset/src/test/java/org/keycloak/benchmark/it/DeploymentIT.java
doc/dataset/modules/ROOT/pages/using-provider.adoc

remove password-hash-iterations from dataset module config

---

.github/workflows/provision-minikube.yml
.github/workflows/rosa-scaling-benchmark.yml
dataset/dataset-import.sh
doc/benchmark/modules/ROOT/pages/scenario/list-sessions.adoc

- Update the position of the threads-count and task-timeout args inside the dataset-import.sh script under dataset module
- Moving back to creating 100k users given the changes in the hashing algo and iterations

Fix removed iterations in docs and minikube CI

---

.github/actions/prometheus-metrics-calc/action.yml
.github/actions/prometheus-run-queries/action.yml
.github/workflows/rosa-multi-az-cluster-undeploy.yml
.github/workflows/rosa-scaling-benchmark.yml
provision/infinispan/ispn-helm/templates/infinispan.yaml

The PR includes the retrieval and inclusion for ISPN "vendor_rpc_manager_average_xsite_replication_time" metric. With this PR jmx is already enabled on ISPN servers, but the statistics is not yet reseted over JMX operation. That will be done with separate PR.
A successful run with generated json file where you can see ispn metrics can be found here: https://github.com/andyuk1986/keycloak-benchmark/actions/runs/8448435155
Relates to #636

Horreum: Include latencies from Infinispan Metrics

---

.gitignore
provision/aws/rosa_efs_create.sh
provision/opentofu/modules/rosa/account-roles/.terraform.lock.hcl
provision/opentofu/modules/rosa/account-roles/provider.tf
provision/opentofu/modules/rosa/hcp/.terraform.lock.hcl
provision/opentofu/modules/rosa/hcp/provider.tf
provision/opentofu/modules/rosa/oidc-provider-operator-roles/.terraform.lock.hcl
provision/opentofu/modules/rosa/oidc-provider-operator-roles/provider.tf
provision/opentofu/modules/rosa/vpc/.terraform.lock.hcl

@ahus1 I messed up the `.gitignore ` on the initial PR, so the *.hcl files weren't included as I thought. This PR addresses that and also upgrades the rhcs provider to the final 1.6.0 version.
Workflow run: https://github.com/ryanemerson/keycloak-benchmark/actions/runs/8540043303

Upgrade to terraform-redhat/rhcs 1.6.0

---

dataset/src/main/resources/META-INF/services/org.keycloak.health.LoadBalancerCheckProviderFactory

`TestMultiSiteLoadBalancerCheckProvider` was removed for 0.10-release (KC 22)  by https://github.com/keycloak/keycloak-benchmark/commit/657b8bc but the dataset module still references it.

Additional removal of reference to `TestMultiSiteLoadBalancerCheckProvider`

---

doc/kubernetes/modules/ROOT/pages/openshift/installation-openshift.adoc
provision/keycloak-tasks/Utils.yaml
provision/keycloak-tasks/olm.sh
provision/keycloak-tasks/olm/templates/operatorgroup.yaml
provision/keycloak-tasks/olm/templates/subscription.yaml
provision/openshift/Taskfile.yaml
provision/openshift/isup.sh

Added a new task `install-keycloak-operator-olm` to `provisioning/keycloak-tasks/Utils.yaml` as an alternative for the currently used task `install-keycloak-operator`.
Depending on a boolean parameter `KC_OPERATOR_OLM` either `install-keycloak-operator` or `install-keycloak-operator-olm` will be used in `provision/openshift/Taskfile.yaml`.
Additional parameters for the OLM task are:
- `KC_OPERATOR_CATALOG_SOURCE_NS` - defaults to `openshift-marketplace`
- `KC_OPERATOR_CATALOG_SOURCE` - defaults to `community-operators`
- `KC_OPERATOR_NAME` - defaults to `keycloak-operator`
- `KC_OPERATOR_CHANNEL` - defaults to the default channel of the selected product
- `KC_OPERATOR_VERSION` - defaults to the latest version in the selected channel
There is no documentation yet. I wanted to collect some …

Support for installing Keycloak Operator via Operator Lifecycle Manager

---

provision/keycloak-tasks/olm.sh

Use `kubectl patch` instead of the `kubectl get | jq | kubectl apply` approach.
Also patch the role definition in the operator's Cluster Service Version (CSV) in case OLM decides to recreate the role.

Improve workaround for issue #28638.

---

provision/openshift/Taskfile.yaml

Only use the OLM task when `KC_OPERATOR_OLM` is set to `true`.

Fix the handling of the `KC_OPERATOR_OLM` flag.

---

provision/aws/rds/aurora_create.sh

fixes #747 
starting off with only single aurora and we can propagate this to global aurora when the need comes around and we are satisfied with this feature addition.
working run: https://github.com/kami619/keycloak-benchmark/actions/runs/8710122179/job/23891308694#step:4:182

enable single aurora perf insights by default

---

.github/actions/keycloak-restart-pods/action.yml
.github/workflows/rosa-scaling-benchmark.yml

- I tried to do this with Keycloak CRD and annotating the restart time, but it was not working, hence fell back to using the reliable delete all pods method.

restart pods after dataset is created in rosa scaling benchmark for scheduled and on demand runs

---

dataset/dataset-import.sh
dataset/src/main/java/org/keycloak/benchmark/dataset/DatasetResourceProvider.java
dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java
doc/dataset/modules/ROOT/pages/using-provider.adoc

Added options `-g ALGORITHM` and `-i ITERATIONS` to the `dataset-import.sh` script for adjusting the realm password policy. Both are optional. The `DatasetResourceProvider` will only apply the options which were provided.

Added dataset options for setting password hashing algorithm and iterations.

---

.github/workflows/rosa-cluster-create.yml
.github/workflows/rosa-multi-az-cluster-create.yml
provision/aws/rosa_create_cluster.sh
provision/aws/rosa_efs_create.sh
provision/opentofu/modules/rosa/hcp/main.tf
provision/opentofu/modules/rosa/hcp/output.tf
provision/opentofu/modules/rosa/hcp/variables.tf

Fixes #788
[Action run](https://github.com/ryanemerson/keycloak-benchmark/actions/runs/8877635506/job/24371626555). Failure is due to EFS timeout. I have added an additional commit since to further increase this.

HCP worker nodes always created in Availability Zone A. Fixes #788

---

.github/actions/prometheus-metrics-calc/action.yml
.github/actions/prometheus-run-queries/action.yml
.github/workflows/rosa-scaling-benchmark.yml

Updated ISPN Metrics calculation.

---

.github/workflows/rosa-cluster-auto-provision-on-schedule.yml
.github/workflows/rosa-multi-az-cluster-create.yml
.github/workflows/rosa-multi-az-cluster-undeploy.yml
.github/workflows/rosa-scaling-benchmark.yml
provision/aws/rosa_create_cluster.sh
provision/common/Taskfile.yaml
provision/minikube/keycloak/templates/sqlpad.yaml

Fixes #785 
Note: this will allow the test results from persistent sessions to goto horreum now, but with some additional work @andyuk1986 confirmed we would be able to filter them out based on the deployment context we are updating the upcoming horreum report schema changes.

persistent sessions load test added to the workflow

---

.github/workflows/rosa-cluster-auto-provision-on-schedule.yml

Since we already created the dataset when running regular benchmark, we do not need to create it again for persistent sessions.

Do not create dataset twice

---

provision/infinispan/ispn-helm/Chart.yaml
provision/infinispan/ispn-helm/templates/infinispan.yaml
provision/infinispan/ispn-helm/values.yaml
provision/minikube/keycloak/config/kcb-infinispan-cache-config.xml
provision/minikube/keycloak/config/kcb-infinispan-cache-remote-store-config.xml

The Operator PR finally got merged, so we should be good to reapply my original fix: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4512

Reapply "Upgrade to Infinispan 15.0.3.Final"

---

.github/actions/keycloak-restart-pods/action.yml
.github/workflows/rosa-scaling-benchmark.yml
benchmark/src/main/content/bin/kc-rolling-restart.sh

- using rolling restart to reset memory of the pods after the dataset creation
- plugged it into the github workflow
I ran it on my github fork here are the results : https://github.com/kami619/keycloak-benchmark/actions/runs/9098888946/job/25010163982
fixes #799

use rolling restart of pods for rosa scaling benchmark

---

doc/benchmark/modules/ROOT/pages/report/rosa-benchmark-key-results.adoc

fixes #744 
- updated the ROSA Key results page with relevant info to Argon2 hashing changes
- removed duplicated parts between Keycloak sizing guide and docs in the keycloak-benchmark
- left the setup part as is to let the users follow along without too many context switches

update docs argon2

---

.github/actions/prometheus-metrics-calc/action.yml
.github/actions/prometheus-run-queries/action.yml

[Horreum] Infinispan metric calculation sometimes results to division to 0 #832

---

provision/infinispan/Utils.yaml
provision/infinispan/ispn-helm/persistent-session-caches.yaml
provision/infinispan/ispn-helm/templates/infinispan.yaml

Deploy Infinispan with maxCount=10000 and num_owners=1

---

.github/workflows/oc-namespace-delete.yml
provision/openshift/delete-namespace.sh

fixes #844 
A working workflow run - https://github.com/kami619/keycloak-benchmark/actions/runs/9403463979/job/25900073424
Another working run with a custom project name `kamesh-keycloak` - https://github.com/kami619/keycloak-benchmark/actions/runs/9403617989/job/25900583038

add a delete namesapce workflow for multi-az deploy and use it in scheduled CI workflow

---

dataset/src/main/java/org/keycloak/benchmark/dataset/ExecutorHelper.java

According the the JavaDoc a future is also done when it failed. The current code will only show exceptions if a task that the code is waiting for is failing with an exception. Any other task that failed in the meantime is silently ignored.
Closes #847

Don't ignore exceptions from tasks

---

.github/actions/rosa-cli-setup/action.yml

Closes #821 
ROSA [v1.2.40](https://github.com/openshift/rosa/releases/tag/v1.2.40) is now available, so we should be able to use the latest release once again.

Fix rosa failure to edit scaling machinepool

---

pom.xml
provision/infinispan/ispn-helm/templates/infinispan.yaml
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/pom.xml
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/LoginLogoutTest.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/DatacenterInfo.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/ExternalInfinispanClient.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/InfinispanClient.java

* Enables protostream encoding in the external Infinispan
* Changes the testsuite to use the Hot Rod client
Closes #628
I have the following error with status code 500. I haven't figured out where they come from. I couldn't find any exceptions in the pod's log. 
```
[ERROR]   EntityReplicationTest.keycloakEntityReplicationOverCacheTest:25 » InternalServerError HTTP 500 Internal Server Error
[ERROR]   SessionExpirationTest.sessionExpirationTest:19 » InternalServerError HTTP 500 Internal Server Error
```
We probably need to fork the `main` branch before merging this one. The forked branch will keep compatibility with jboss-marshalling and KC25.

Enable protostream

---

.github/actions/keycloak-create-deployment/action.yml
.github/workflows/rosa-cluster-auto-provision-on-schedule.yml
.github/workflows/rosa-multi-az-cluster-create.yml
provision/common/Taskfile.yaml
provision/keycloak-tasks/Taskfile.yaml
provision/keycloak-tasks/Utils.yaml
provision/minikube/keycloak/templates/keycloak.yaml
provision/minikube/keycloak/values.yaml
provision/openshift/Taskfile.yaml

* New option to enable external infinispan feature (disabled by default)
* Added to the nightly runs to get some numbers
It has been a while since I looked at those GH action files. Please double-check if I did it right. 
I tested a deployment with `KC_EXTERNAL_INFINISPAN=true` and confirmed no embedded caches were present in Keycloak Servers.

Enable External Infinispan Feature

---

benchmark/pom.xml
dataset/pom.xml
doc/benchmark/antora.yml
doc/dataset/antora.yml
doc/kubernetes/antora.yml
pom.xml
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/pom.xml

Updating the snapshot version after the release of 0.13 of Keycloak Benchmark.

Update the snapshot version after release.

---

.github/workflows/rosa-multi-az-cluster-delete.yml

Minor fix. Here's a run on my fork where the affected job passed (later one failed, but not relevant): https://github.com/ryanemerson/keycloak-benchmark/actions/runs/9714499539

Fix Active/Active multi-az delete

---

.github/workflows/rosa-cluster-auto-provision-on-schedule.yml
doc/kubernetes/modules/ROOT/pages/running/loadbalancing.adoc
doc/kubernetes/modules/ROOT/pages/running/take-active-site-offline.adoc
provision/infinispan/ispn-helm/templates/infinispan-alerts.yaml
provision/openshift/cluster-monitoring-config.yaml
provision/opentofu/modules/aws/accelerator/main.tf
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/pom.xml
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/AbstractCrossDCTest.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/FailoverTest.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/AWSClient.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/DatacenterInfo.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/PrometheusClient.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/util/K8sUtils.java

Closes #854
The source of the original failures was fixed by https://github.com/keycloak/keycloak/pull/30841
However, when investigating the issue I realised that the testsuite was very flaky and failures often occurred when executing the `FailoverTest` in conjunction with the other tests. This PR reenables the active-active tests as well adding several fixes/improvements to the testsuite to reduce the chance of flaky failures.

Active active test fix

---

provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/LoginLogoutTest.java

Disable tests that manually manipulate data in the external Infinispan. Keycloak is unable to find the data and does not act properly.
Those tests are useful with Persistent Sessions only

Disable tests for External Infinispan feature

---

.github/workflows/rosa-cluster-auto-provision-on-schedule.yml
.github/workflows/rosa-run-crossdc-func-tests.yml
provision/minikube/keycloak/templates/keycloak.yaml
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/run-crossdc-tests.sh
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/AbstractCrossDCTest.java

This addition changes current deployment to always disable caches when persistent sessions are used in multi site setup. 
Here is a test run: https://github.com/mhajas/keycloak-benchmark/actions/runs/10111381036/job/27963206863

Fix A/A deployment to not use caches

---

.github/workflows/rosa-cluster-auto-provision-on-schedule.yml

Fixes #900 
Trim the ROSA Scheduled workflow to only two combinations
- ROSA Scheduled Create Active/Active cluster with Volatile Sessions and External Infinispan
- ROSA Scheduled Create Active/Active cluster with Persistent Sessions and External Infinispan
Working run: https://github.com/kami619/keycloak-benchmark/actions/runs/10123478369

optimize rosa scheduled workflow to run reduced combinations

---

.github/workflows/rosa-multi-az-cluster-create.yml
provision/aws/global-accelerator/accelerator_multi_az_create.sh
provision/opentofu/modules/aws/accelerator/.terraform.lock.hcl
provision/opentofu/modules/aws/accelerator/main.tf
provision/opentofu/modules/aws/accelerator/output.tf

Closes #911
Successful deployment: https://github.com/ahus1/keycloak-benchmark/actions/runs/10246749685/job/28344593381:
```
[global-accelerator-create] ACCELERATOR DNS: a16fa9b0d684c08cd.dualstack.awsglobalaccelerator.com
[global-accelerator-create] ACCELERATOR WEBHOOK: https://jy45j74qcvri4cgf3nbmcpel7u0fqcon.lambda-url.eu-west-1.on.aws/
```

Support IPv6 for global accelerator

---

provision/infinispan/ispn-helm/values.yaml

Use PESSIMISTIC transaction mode as default. It is faster for single key operations like put/remove/replace
I changed the default value in the task file [1] but forgot to update the helms chart. 
[1] https://github.com/keycloak/keycloak-benchmark/blob/main/provision/infinispan/Utils.yaml#L106

Use the same default value in helms chart and taskfile

---

.gitignore
benchmark/src/main/python/README.adoc
benchmark/src/main/python/perfInsights.py
benchmark/src/main/python/requirements.txt
doc/kubernetes/modules/ROOT/pages/util/perf-insights.adoc
doc/kubernetes/modules/ROOT/partials/util-nav.adoc

We are adding a script to analyze the generated performance test run results efficiently.
usage:
python perfInsights.py <directory_on_result_data_github_branch> <outputDir>
```
python perfInsights.py rosa_scalability/2024/07/23 results
```
Sample Output: https://github.com/user-attachments/files/16390815/rosa_scalability_runs_comparision.zip

add new perfInsights.py script to analyse the data generated in result_data branch

---

.github/workflows/rosa-cluster-auto-provision-on-schedule.yml
.github/workflows/rosa-multi-az-cluster-create.yml
provision/aws/global-accelerator/accelerator_multi_az_delete.sh
provision/infinispan/Utils.yaml
provision/infinispan/ispn-helm/values.yaml
provision/opentofu/modules/aws/accelerator/src/stonith_lambda.py

Reinstate WARN on backup failures until take-offline configuration in place, plus misc fixes to deployment scripts/actions.
This will fix the testsuite for deployments with persistent sessions, however a 401 is still thrown when testing with volatile sessions.

Testsuite fixes

---

.github/actions/prometheus-metrics-calc/action.yml
.github/workflows/rosa-scaling-benchmark.yml
benchmark/src/main/python/perfInsights.py

fixes #914 
- Enables metrics gathering from both clusters for CPU Util of Logins, Credential grants, and Memory stats.
Working run: https://github.com/kami619/keycloak-benchmark/actions/runs/10355460317/job/28663154007
Working result JSON: https://github.com/kami619/keycloak-benchmark/blob/result-data/rosa_scalability/2024/08/12/result-20240812-161728-54455ba4-0cfb-4388-ac58-4031874c65f0.json
I created a [follow-up task to clean up the way](https://github.com/keycloak/keycloak-benchmark/issues/925) we are running Prometheus queries and performing the calculations, including repeating the login steps multiple times to fetch the THANOS host values and OC tokens.

extend the prometheus queries to both clusters

---

.github/workflows/rosa-multi-az-cluster-create.yml
provision/infinispan/Utils.yaml
provision/infinispan/ispn-helm/values.yaml
provision/opentofu/modules/aws/accelerator/src/stonith_lambda.py
provision/rosa-cross-dc/Taskfile.yaml
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/AbstractCrossDCTest.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/FailoverTest.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/AWSClient.java
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/client/ExternalInfinispanClient.java

STONITH Lambda updated so the backup site of the "winning" AZ is explicitly taken offline. This is necessary in order for us to utilise a FAIL xsite strategy, as without it, the winning AZ would not be able to continue to serve user requests.
This approach requires the user to perform additional configuration steps:
1. A "infinispan" label must be added to the `PrometheusAlert` definition in each site. This label contains the exposed URL of the Infinispan cluster in that site.
2. An Infinispan username and password must be configured in the Lambda. The password should be retrieved via the AWS SecretsManager the same as the Keycloak password.
In order to allow 1. in our scripts, I have created an additional task "deploy-xsite-infinispan-monitoring".
Closes #930

Take sites offline on split-brain

---

benchmark/src/main/content/bin/kc-rolling-restart.sh

Example usage:
```
> export PROJECT=kamesh-keycloak
> export POD_LABEL="infinispan-pod"
> ./kc-rolling-restart.sh
INFO:2024-09-05-09:52:42-EDT Deleting all infinispan-pod pods in sequence
NAME           READY   STATUS    RESTARTS   AGE
infinispan-0   1/1     Running   0          2m27s
infinispan-1   1/1     Running   0          22h
infinispan-2   1/1     Running   0          22h
INFO:2024-09-05-09:52:42-EDT Killing Pod 'infinispan-0'
pod "infinispan-0" deleted
infinispan.infinispan.org/infinispan condition met
INFO:2024-09-05-09:53:01-EDT infinispan-pod pod infinispan-0 took 16 seconds to recover
NAME           READY   STATUS    RESTARTS   AGE
infinispan-0   1/1     Running   0          16s
infinispan-1   1/1     Running   0          22h
infinispan-2   1/1     Running   0          22h …
```

kc-rolling-restart.sh is enhanced to do a rolling restart on Infinispan pods

---

.github/actions/keycloak-restart-pods/action.yml

Attempt to fix the nighty build: https://github.com/keycloak/keycloak-benchmark/actions/runs/10732714803/job/29766161807

Set missing POD_LABEL environment variable in GHA

---

provision/opentofu/modules/aws/accelerator/src/stonith_lambda.py
provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/src/test/java/org/keycloak/benchmark/crossdc/AbstractCrossDCTest.java

Closes #974
The current implementation is checking the status in the lambda, however, this could be theoretically improved to not call the lambda at all on the resolved event. However, I was not able to create a new [matcher](https://github.com/keycloak/keycloak-benchmark/blob/2cd91028bddfea8e05acabb2354894319d28503b/provision/infinispan/ispn-helm/templates/infinispan-alerts.yaml#L25) for the status as it seems the matcher works only on labels. 
I also tried to add a new alert label with the metric value, however, it reported 0 even for resolved alert :/. [Here](https://github.com/keycloak/keycloak-benchmark/blob/2cd91028bddfea8e05acabb2354894319d28503b/provision/infinispan/ispn-helm/templates/infinispan-alerts.yaml#L59) I did the following:
```
- alert: SiteOffline
expr: min by …
```

Fix lambda removing site when site view was recovered

---

.github/actions/get-keycloak-url/action.yml
doc/kubernetes/modules/ROOT/pages/util/healthchecks-keycloak.adoc
provision/rosa-cross-dc/cross-site-health-checks.sh

Fixes #980 
The updated script works against the A/A deployments.
```
> ./cross-site-health-checks.sh -d ae3df5446dfc4f4e2.dualstack.awsglobalaccelerator.com \
-u developer -p $ISPN_PWD \
-s gh-keycloak-a.lsja.p3.openshiftapps.com \
-c 3 -n runner-keycloak
Verify the Keycloak Load Balancer health check
Checking health for: https://ae3df5446dfc4f4e2.dualstack.awsglobalaccelerator.com/lb-check
"HEALTHY"
Verify the Load Balancer health check on the Site
Checking health for: https://aaee0689882944bb780191449cbfd791-78a0ef5dd6a41017.elb.eu-west-1.amazonaws.com/lb-check
"HEALTHY"
Verify the default cache manager health in external ISPN
Checking health for: https://infinispan-external-runner-keycloak.apps.rosa.gh-keycloak-a.lsja.p3.openshiftapps.com/rest/v2/cache-managers/default/health/status …
```

updated the cross site health check script to suit the new deployments

---

.github/actions/prometheus-metrics-calc/action.yml
.github/actions/prometheus-run-queries/action.yml

Updated the ISPN cache name as the sessions are stored in DB now. Chosen `authenticationSessions` cache, as it is used while login. After KC works mainly with DB.

Changed the ispn cache name for which the metric should be retrieved.

---

.github/workflows/keycloak-multi-site-health-check.yml
.github/workflows/rosa-cluster-auto-provision-on-schedule.yml
provision/aws/route53/route53_fetch_domain.sh

This PR addresses,
- Addition of script to fetch the Route53 domain dynamically and then construct the Keycloak Site Url.
- Add the health checks for Route 53 to the scheduled workflow.
Example Output of the script,
```
> DOMAIN=$(./route53_fetch_domain.sh "keycloak-benchmark.com.")
> echo $DOMAIN
gh-keycloak-a-gh-keycloak-b-mjqxmdyk.keycloak-benchmark.com
```

update health checks to work for both A/A and A/P deployments

---

provision/infinispan/Utils.yaml
provision/infinispan/ispn-helm/templates/infinispan.yaml
provision/infinispan/ispn-helm/values.yaml

Indexing is broken in Infinispan 15.0.8.Final. Use the following image if you want to try it
```
CROSS_DC_IMAGE=quay.io/pruivo/infinispan-server:15.0.9.Final-1
```
`CROSS_DC_INDEXES` taskfile variable enables it.

Infinispan indexing switch

---

.github/workflows/rosa-cluster-auto-provision-on-schedule.yml

* Adds volatile active/active deployment testing and benchmarking.
* Disables active/passive benchmarking only.
Closes #1013

Re-enable volatile active/active testing

---

.github/workflows/rosa-scaling-benchmark.yml
provision/rosa-cross-dc/Taskfile.yaml

* Current performance run is (over)loading the DB too much (98% CPU)
* Reduce the total number of clients to 10k (75% cache hit ratio)
* Reduce the requests per second to 750 (25% reduction)
Closes #1018

Reduce ClientSecrets scenario load

---

doc/kubernetes/modules/ROOT/pages/running/metrics/jvm_metrics.adoc
provision/openshift/monitoring/dashboards/keycloak-perf-tests.json

It seems `jvm_gc_overhead_percent` was renamed to `jvm_gc_overhead`.

Fix jvm_gc_overhead metric name

---

.github/workflows/README.md
.github/workflows/rosa-cluster-create.yml
doc/benchmark/modules/ROOT/pages/report/rosa-benchmark-key-results.adoc
doc/kubernetes/modules/ROOT/pages/prerequisite/prerequisite-rosa.adoc
provision/aws/rosa_create_cluster.sh
provision/keycloak-tasks/keycloak-image-helm/templates/keycloak-nightly-imagestream.yaml
provision/minikube/keycloak/templates/keycloak.yaml
provision/opentofu/modules/rosa/hcp/variables.tf

Update to ARM worker node types

---

doc/kubernetes/collector/build.sh
provision/infinispan/ispn-helm/templates/infinispan.yaml
provision/infinispan/ispn-helm/values.yaml

Cleanup and improve Infinispan template

---

.github/workflows/rosa-cluster-auto-provision-on-schedule.yml

This reverts this PR: https://github.com/keycloak/keycloak-benchmark/pull/1081/files

Enable rosa-cluster-auto-provision-on-schedule.yml after holidays

---

.github/workflows/provision-minikube.yml

Adding repo check to the on-schedule GHA for minikube CI (same as for other on-schedule GHAs).

Add `github.repository` check to the minikube CI GHA.

---

.gitignore
provision/minikube/Taskfile.yaml
provision/minikube/isup.sh
provision/minikube/keycloak/templates/keycloak-monitor.yaml
provision/minikube/keycloak/templates/sqlpad.yaml
provision/minikube/loki.yaml
provision/minikube/monitoring.yaml

- **Upgrade to kube-prometheus-stack 69.7.3**
- **Upgrade Jaeger to 3.4.0**
- **Upgrade Loki to 6.27.0**
- **Upgrade promtail to 6.16.6**
- **Don't track keycloak-grafana-dashboard**
All appears to be working as expected on my local `minikube` cluster. I wanted to utilise Jaeger v2, but it seems that's not currently possible with the helm chart https://github.com/jaegertracing/helm-charts/issues/610.

monitoring upgrades

---

provision/opentofu/modules/rosa/hcp/variables.tf

Upgrading OCP version to the latest 4.17 supported by ROSA.
List of currently supported versions: [4.18.5 4.18.4 4.18.3 4.18.2 4.18.1 4.17.20
│ 4.17.19 4.17.18 4.17.17 4.17.16 4.17.15 4.16.37 4.16.36 4.16.35 4.16.34
│ 4.15.47 4.15.46 4.15.45 4.14.48 4.14.46 4.14.45 4.14.44 4.14.43 4.14.42
│ 4.14.41 4.14.40 4.14.39 4.14.38 4.14.37 4.14.36 4.14.35 4.14.34 4.14.33
│ 4.14.32 4.14.31 4.14.30 4.14.29 4.14.28 4.13.55 4.13.54 4.13.53 4.13.52
│ 4.13.51 4.13.50 4.13.49 4.13.48 4.13.46 4.13.45 4.13.44 4.13.43 4.13.42
│ 4.13.41 4.13.40 4.13.39 4.13.38 4.13.37 4.13.36 4.13.35 4.13.34 4.13.33
│ 4.13.32 4.13.31 4.13.30 4.13.29 4.13.28 4.13.27 4.13.26 4.13.25 4.13.24
│ 4.13.23 4.13.22 4.13.21 4.13.19 4.13.18 4.13.17 4.13.15 4.13.14 4.13.13
│ 4.13.12 4.13.11 4.13.10]

Upgraded ROSA OCP to 4.17.20.

---

provision/opentofu/modules/rosa/hcp/variables.tf

Upgrading OCP version to the latest 4.16 supported by ROSA.
List of currently supported versions: [4.18.5 4.18.4 4.18.3 4.18.2 4.18.1 4.17.20
│ 4.17.19 4.17.18 4.17.17 4.17.16 4.17.15 4.16.37 4.16.36 4.16.35 4.16.34
│ 4.15.47 4.15.46 4.15.45 4.14.48 4.14.46 4.14.45 4.14.44 4.14.43 4.14.42
│ 4.14.41 4.14.40 4.14.39 4.14.38 4.14.37 4.14.36 4.14.35 4.14.34 4.14.33
│ 4.14.32 4.14.31 4.14.30 4.14.29 4.14.28 4.13.55 4.13.54 4.13.53 4.13.52
│ 4.13.51 4.13.50 4.13.49 4.13.48 4.13.46 4.13.45 4.13.44 4.13.43 4.13.42
│ 4.13.41 4.13.40 4.13.39 4.13.38 4.13.37 4.13.36 4.13.35 4.13.34 4.13.33
│ 4.13.32 4.13.31 4.13.30 4.13.29 4.13.28 4.13.27 4.13.26 4.13.25 4.13.24
│ 4.13.23 4.13.22 4.13.21 4.13.19 4.13.18 4.13.17 4.13.15 4.13.14 4.13.13
│ 4.13.12 4.13.11 4.13.10]

Upgraded ROSA OCP to 4.16.37.

---

pom.xml

The version is set to `999.0.0-SNAPSHOT` which is not backward-compatible.

Set `keycloak.version` property in `0.14-release` branch to `26.0.4` for admin API compatibility.

---

.github/workflows/rosa-scheduled-run.yml
.github/workflows/rosa-single-cluster-benchmark.yml

I added a suffix to the benchmark AWS cluster as I'm concerned that they may interfere with each other due to the same `github.run_id`

Schedule stretched cluster run

---

benchmark/src/main/content/bin/kcb.sh

Closes #1197
Successful run of the benchmarks on my fork: https://github.com/ryanemerson/keycloak-benchmark/actions/runs/17409642029

Benchmark workflows failing due to multiple jars in benchmark distribution
